// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client'
import { client } from './client.gen'
import type {
  ClockSyncData,
  ClockSyncErrors,
  ClockSyncResponses,
  GetDeviceCapabilitiesData,
  GetDeviceCapabilitiesResponses,
  GetDeviceInfoData,
  GetDeviceInfoResponses,
  GetDeviceSessionIdsData,
  GetDeviceSessionIdsResponses,
  GetDeviceTimeInfoData,
  GetDeviceTimeInfoErrors,
  GetDeviceTimeInfoResponses,
  GetEventsData,
  GetEventsResponses,
  GetHampStateData,
  GetHampStateResponses,
  GetHspStateData,
  GetHspStateResponses,
  GetHsspStateData,
  GetHsspStateResponses,
  GetHvpStateData,
  GetHvpStateResponses,
  GetModeData,
  GetModeResponses,
  GetOffsetData,
  GetOffsetErrors,
  GetOffsetResponses,
  GetServerTimeData,
  GetServerTimeResponses,
  GetSliderSettingsData,
  GetSliderSettingsResponses,
  GetSlideStateData,
  GetSlideStateResponses,
  GetStatisticsData,
  GetStatisticsResponses,
  GetStreamStateData,
  GetStreamStateResponses,
  GetStrokeData,
  GetStrokeErrors,
  GetStrokeResponses,
  HspAddData,
  HspAddResponses,
  HspFlushData,
  HspFlushResponses,
  HspPauseData,
  HspPauseResponses,
  HspPlayData,
  HspPlayResponses,
  HspResumeData,
  HspResumeResponses,
  HspSetupData,
  HspSetupResponses,
  HspStopData,
  HspStopResponses,
  HsspPauseData,
  HsspPauseResponses,
  HsspPlayData,
  HsspPlayResponses,
  HsspResumeData,
  HsspResumeResponses,
  HsspSetupData,
  HsspSetupResponses,
  HsspStopData,
  HsspStopResponses,
  HvpStartData,
  HvpStartResponses,
  HvpStopData,
  HvpStopResponses,
  IsConnectedData,
  IsConnectedErrors,
  IsConnectedResponses,
  IssueTokenData,
  IssueTokenErrors,
  IssueTokenResponses,
  SendXatData,
  SendXatResponses,
  SendXavaData,
  SendXavaResponses,
  SendXavpData,
  SendXavpResponses,
  SendXptData,
  SendXptResponses,
  SendXpvaData,
  SendXpvaResponses,
  SendXpvpData,
  SendXpvpResponses,
  SetHampStrokeData,
  SetHampStrokeResponses,
  SetHampVelocityData,
  SetHampVelocityResponses,
  SetHspLoopData,
  SetHspLoopResponses,
  SetHspPauseOnStarvingData,
  SetHspPauseOnStarvingResponses,
  SetHspPaybackRateData,
  SetHspPaybackRateResponses,
  SetHspThresholdData,
  SetHspThresholdResponses,
  SetHspTimeData,
  SetHspTimeResponses,
  SetHsspTimeData,
  SetHsspTimeResponses,
  SetHvpStateData,
  SetHvpStateResponses,
  SetMode2Data,
  SetMode2Responses,
  SetModeData,
  SetModeResponses,
  SetOffsetData,
  SetOffsetErrors,
  SetOffsetResponses,
  SetStreamTimeData,
  SetStreamTimeResponses,
  SetStrokeData,
  SetStrokeResponses,
  SetupStreamData,
  SetupStreamResponses,
  StartHampData,
  StartHampResponses,
  StopHampData,
  StopHampResponses,
  StreamPlayData,
  StreamPlayResponses,
  StreamStopData,
  StreamStopResponses,
} from './types.gen'
import {
  zClockSyncData,
  zClockSyncResponse,
  zGetDeviceCapabilitiesData,
  zGetDeviceCapabilitiesResponse,
  zGetDeviceInfoData,
  zGetDeviceInfoResponse,
  zGetDeviceSessionIdsData,
  zGetDeviceSessionIdsResponse,
  zGetDeviceTimeInfoData,
  zGetDeviceTimeInfoResponse,
  zGetEventsData,
  zGetEventsResponse,
  zGetHampStateData,
  zGetHampStateResponse,
  zGetHspStateData,
  zGetHspStateResponse,
  zGetHsspStateData,
  zGetHsspStateResponse,
  zGetHvpStateData,
  zGetHvpStateResponse,
  zGetModeData,
  zGetModeResponse,
  zGetOffsetData,
  zGetOffsetResponse,
  zGetServerTimeData,
  zGetServerTimeResponse,
  zGetSliderSettingsData,
  zGetSliderSettingsResponse,
  zGetSlideStateData,
  zGetSlideStateResponse,
  zGetStatisticsData,
  zGetStatisticsResponse,
  zGetStreamStateData,
  zGetStreamStateResponse,
  zGetStrokeData,
  zGetStrokeResponse,
  zHspAddData,
  zHspAddResponse,
  zHspFlushData,
  zHspFlushResponse,
  zHspPauseData,
  zHspPauseResponse,
  zHspPlayData,
  zHspPlayResponse,
  zHspResumeData,
  zHspResumeResponse,
  zHspSetupData,
  zHspSetupResponse,
  zHspStopData,
  zHspStopResponse,
  zHsspPauseData,
  zHsspPauseResponse,
  zHsspPlayData,
  zHsspPlayResponse,
  zHsspResumeData,
  zHsspResumeResponse,
  zHsspSetupData,
  zHsspSetupResponse,
  zHsspStopData,
  zHsspStopResponse,
  zHvpStartData,
  zHvpStartResponse,
  zHvpStopData,
  zHvpStopResponse,
  zIsConnectedData,
  zIsConnectedResponse,
  zIssueTokenData,
  zIssueTokenResponse,
  zSendXatData,
  zSendXatResponse,
  zSendXavaData,
  zSendXavaResponse,
  zSendXavpData,
  zSendXavpResponse,
  zSendXptData,
  zSendXptResponse,
  zSendXpvaData,
  zSendXpvaResponse,
  zSendXpvpData,
  zSendXpvpResponse,
  zSetHampStrokeData,
  zSetHampStrokeResponse,
  zSetHampVelocityData,
  zSetHampVelocityResponse,
  zSetHspLoopData,
  zSetHspLoopResponse,
  zSetHspPauseOnStarvingData,
  zSetHspPauseOnStarvingResponse,
  zSetHspPaybackRateData,
  zSetHspPaybackRateResponse,
  zSetHspThresholdData,
  zSetHspThresholdResponse,
  zSetHspTimeData,
  zSetHspTimeResponse,
  zSetHsspTimeData,
  zSetHsspTimeResponse,
  zSetHvpStateData,
  zSetHvpStateResponse,
  zSetMode2Data,
  zSetMode2Response,
  zSetModeData,
  zSetModeResponse,
  zSetOffsetData,
  zSetOffsetResponse,
  zSetStreamTimeData,
  zSetStreamTimeResponse,
  zSetStrokeData,
  zSetStrokeResponse,
  zSetupStreamData,
  zSetupStreamResponse,
  zStartHampData,
  zStartHampResponse,
  zStopHampData,
  zStopHampResponse,
  zStreamPlayData,
  zStreamPlayResponse,
  zStreamStopData,
  zStreamStopResponse,
} from './zod.gen'

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

/**
 * Issue a client API access token.
 *
 * This endpoint generates a client-token for API authentication. The endpoint can only be accessed with an ApplicationKey.
 *
 * A client-token authenticates a client with the device API endpoints that requires authentication. Use it by including the token as a Bearer token in the Authorization header.
 *
 * It can be used in client applications, including web browsers and mobile apps. It's an alternativ to the ApplicationID that should be harder to abuse outside your application's browser environment.
 *
 * A token is valid for a limited time, after which it expires. The default lifetime for a token is 1 hour. You can adjust this lifespan up to a maximum of 24 hours using the `ttl` parameter.
 *
 * A token can be configured with the following optional restrictions:
 * - Device connection key
 * - Client IP
 * - Client Origin
 * - Client Referer
 * - Client User-Agent
 * - Client Accept-Language
 * - Client Accept-Encoding
 * - Client Cache-Control
 *
 * Specifying a device connection key ensures that the token can only be used with a specific device.
 *
 * The client values forms a lightweight client fingerprint that makes it harder to abuse the token outside the client environment.
 *
 * **NOTE**: Issuing a client-token for a specific device does not eliminate the need to include the connection key when sending device commands.
 *
 * The `X-Connection-Key` header is still required for device-specific operations, even if the client-token was issued for that device.
 *
 * ### Token Renewal
 *
 * Alongside the token, you receive a **renew** URL. Use this URL to extend your token's validity, ensuring uninterrupted service for long-running applications.
 *
 * The renew URL remains valid as long as the token is valid. Remember to renew before the token expires; post-expiration, both the token and renew URL become invalid, necessitating a new token issue.
 *
 * The renew operation only extends the token's lifespan. It does not alter initial restrictions (device connection key or other client values) set during token issuance.
 *
 */
export const issueToken = <ThrowOnError extends boolean = false>(
  options?: Options<IssueTokenData, ThrowOnError>,
) =>
  (options?.client ?? client).get<IssueTokenResponses, IssueTokenErrors, ThrowOnError>({
    requestValidator: async (data) => await zIssueTokenData.parseAsync(data),
    responseValidator: async (data) => await zIssueTokenResponse.parseAsync(data),
    security: [{ name: 'X-Api-Key', type: 'apiKey' }],
    url: '/auth/token/issue',
    ...options,
  })

/**
 * Get the current HAMP state of the device.
 *
 * Get the current HAMP state of the device.
 *
 * See the request body schema definition for details.<br><br>See <a href="https://links.handyfeeling.com/docs-api-handy-rest-v3-hamp">Handy Alternate Motion Protocol (HAMP)</a> for additional information about the HAMP protocol and code samples.
 *
 */
export const getHampState = <ThrowOnError extends boolean = false>(
  options: Options<GetHampStateData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetHampStateResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetHampStateData.parseAsync(data),
    responseValidator: async (data) => await zGetHampStateResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/hamp/state',
    ...options,
  })

/**
 * Start the HAMP protocol.
 *
 * Start the HAMP movement.
 *
 * See the request body schema definition for details.<br><br>See <a href="https://links.handyfeeling.com/docs-api-handy-rest-v3-hamp">Handy Alternate Motion Protocol (HAMP)</a> for additional information about the HAMP protocol and code samples.
 *
 */
export const startHamp = <ThrowOnError extends boolean = false>(
  options: Options<StartHampData, ThrowOnError>,
) =>
  (options.client ?? client).put<StartHampResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zStartHampData.parseAsync(data),
    responseValidator: async (data) => await zStartHampResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/hamp/start',
    ...options,
  })

/**
 * Stop the HAMP protocol.
 *
 * Stop the HAMP movement.
 *
 * See the request body schema definition for details.<br><br>See <a href="https://links.handyfeeling.com/docs-api-handy-rest-v3-hamp">Handy Alternate Motion Protocol (HAMP)</a> for additional information about the HAMP protocol and code samples.
 *
 */
export const stopHamp = <ThrowOnError extends boolean = false>(
  options: Options<StopHampData, ThrowOnError>,
) =>
  (options.client ?? client).put<StopHampResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zStopHampData.parseAsync(data),
    responseValidator: async (data) => await zStopHampResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/hamp/stop',
    ...options,
  })

/**
 * Set the HAMP velocity.
 *
 * Set the HAMP velocity.
 *
 * See the request body schema definition for details.<br><br>See <a href="https://links.handyfeeling.com/docs-api-handy-rest-v3-hamp">Handy Alternate Motion Protocol (HAMP)</a> for additional information about the HAMP protocol and code samples.
 *
 */
export const setHampVelocity = <ThrowOnError extends boolean = false>(
  options: Options<SetHampVelocityData, ThrowOnError>,
) =>
  (options.client ?? client).put<SetHampVelocityResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zSetHampVelocityData.parseAsync(data),
    responseValidator: async (data) => await zSetHampVelocityResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/hamp/velocity',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Set the HAMP stroke region.
 *
 * Set the HAMP stroke region. The HAMP stroke region defines the movement range of the device within the current stroke region.
 *
 * See the request body schema definition for details.<br><br>See <a href="https://links.handyfeeling.com/docs-api-handy-rest-v3-hamp">Handy Alternate Motion Protocol (HAMP)</a> for additional information about the HAMP protocol and code samples.
 *
 */
export const setHampStroke = <ThrowOnError extends boolean = false>(
  options: Options<SetHampStrokeData, ThrowOnError>,
) =>
  (options.client ?? client).put<SetHampStrokeResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zSetHampStrokeData.parseAsync(data),
    responseValidator: async (data) => await zSetHampStrokeResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/hamp/stroke',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Get the device slider settings.
 *
 * Get the device slider settings.
 *
 * To change device slider settings, use the Handy onboarding app.
 *
 */
export const getSliderSettings = <ThrowOnError extends boolean = false>(
  options: Options<GetSliderSettingsData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetSliderSettingsResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetSliderSettingsData.parseAsync(data),
    responseValidator: async (data) => await zGetSliderSettingsResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/settings/slider',
    ...options,
  })

/**
 * Get the device information.
 *
 * Get the device information.
 */
export const getDeviceInfo = <ThrowOnError extends boolean = false>(
  options: Options<GetDeviceInfoData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetDeviceInfoResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetDeviceInfoData.parseAsync(data),
    responseValidator: async (data) => await zGetDeviceInfoResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/info',
    ...options,
  })

/**
 * Get the current device mode.
 *
 * Get the current device mode.
 */
export const getMode = <ThrowOnError extends boolean = false>(
  options: Options<GetModeData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetModeResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetModeData.parseAsync(data),
    responseValidator: async (data) => await zGetModeResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/mode',
    ...options,
  })

/**
 * Set the device mode.
 *
 * `DEPRECATEAD`. Use `/mode2` endpoint instead which returns additional information in the response. Kept for backwards compatibility. Set the device mode.
 *
 * @deprecated
 */
export const setMode = <ThrowOnError extends boolean = false>(
  options: Options<SetModeData, ThrowOnError>,
) =>
  (options.client ?? client).put<SetModeResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zSetModeData.parseAsync(data),
    responseValidator: async (data) => await zSetModeResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/mode',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Set the device mode.
 *
 * Set the device mode and returns the active mode and mode_session_id.
 */
export const setMode2 = <ThrowOnError extends boolean = false>(
  options: Options<SetMode2Data, ThrowOnError>,
) =>
  (options.client ?? client).put<SetMode2Responses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zSetMode2Data.parseAsync(data),
    responseValidator: async (data) => await zSetMode2Response.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/mode2',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Check device connectivity.
 *
 * Check if the device with the specific connection key is connected.
 *
 * This is the fastest way to check device connectivity.
 *
 * To receive continouos updates on device connectivity and device state use the SSE endpoint to subscribe to device events.
 *
 */
export const isConnected = <ThrowOnError extends boolean = false>(
  options: Options<IsConnectedData, ThrowOnError>,
) =>
  (options.client ?? client).get<IsConnectedResponses, IsConnectedErrors, ThrowOnError>({
    requestValidator: async (data) => await zIsConnectedData.parseAsync(data),
    responseValidator: async (data) => await zIsConnectedResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/connected',
    ...options,
  })

/**
 * Subscribe to device events over SSE.
 *
 * Starts a Server-Sent Events (SSE) stream for real-time updates on device events.
 * It's an efficient way to receive continuous updates on device connectivity, mode changes, and other relevant events without the need to poll API endpoints.
 * To reveive events for a single device, specify the device connection key with the `ck` query parameter.
 * To receive events for multiple devices, a channel reference can be specified with the `ck` query parameter. This will receive events from all channel subcribers.
 * Optionally filter events by specifying the `events` query parameter. If not specified, all events are pushed to the client.
 * Ex. events=device_connected,device_disconnected
 *
 * **NOTE1:**The Swagger UI does not support SSE, so you can not directly test the endpoint from this page. The endpoint works with any SSE-compatible client, such as a browser or a dedicated SSE client.
 *
 * **NOTE2:**The endpoint requires authentication. Since SSE does not support headers, the credentials must be passed as a query parameter (apikey). You can use an ApplicationID or an issued client token as the apikey value.
 *
 * This Handy v3 OpenAPI specification defines schema definitions for each event type. If you use a code generation tool that generates schemas, you should be able to use these types when parsing the SSE stream events.
 *
 * The SSE stream provides the following events:
 * - `battery_changed` Received when the battery status have changed.
 * - `ble_status_changed` Received when the BLE status have changed.
 * - `button_event` Received in case of an unhandled button event. Eg. the user uses a device button in a way ignored by the current device mode.
 * - `device_clock_synchronized` Received when the device clock have finished synchronization with the server clock.
 * - `device_connected` Received when the device connects.
 * - `device_disconnected` Received when the device disconnects.
 * - `device_error` Received when a device error occurs.
 * - `device_status` Received when starting the SSE connection.
 * - `hamp_state_changed` Received when the HAMP state have changed.
 * - `hrpp_state_changed` Received when the HRPP state have changed.
 * - `hdsp_state_changed` Received when the HDSP state have changed.
 * - `hsp_looping` Received when the HSP starts a new loop.
 * - `hsp_starving` Received when the HSP is starving (no more data to play). Only sent if pause_on_starving is disabled.
 * - `hsp_state_changed` Received when the HSP state have changed.
 * - `hsp_threshold_reached` Received when the HSP data threshold is reached.
 * - `hsp_paused_on_starving` Received when the HSP is paused due to starvation. Only sent if pause_on_starving is enabled.
 * - `hsp_resumed_on_not_starving` Received when the HSP is resumed after starvation and playable data is available. Only sent if pause_on_starving is enabled.
 * - `stream_end_reached` Received when the end of a closed stream have been reached. This includes scripts played with the HSSP protocol or closed streams played with STREAM protocol.
 * - `hvp_state_changed` Received when the HVP state changes.
 * - `low_memory_error` Received when the device failed to handle some command due to memory limitations.
 * - `low_memory_warning` Received when the device's available free memory is critically low.
 * - `mode_changed` Received when the device mode have changed.
 * - `ota_progress` Received when the OTA progress have changed.
 * - `slider_blocked` Received when the slider is blocked.
 * - `slider_unblocked` Received when the slider is unblocked.
 * - `stroke_changed` Received when the stroke region have changed.
 * - `temp_high` Received when the device temperature is high.
 * - `temp_ok` Received when the device temperature is back to normal.
 * - `wifi_scan_complete` Received when a device wifi scan have completed.
 * - `wifi_status_changed` Received when the wifi status have changed.
 *
 * See [Handy v3 API documentation](https://ohdoki.notion.site/Handy-API-v3-ea6c47749f854fbcabcc40c729ea6df4) for more information and code samples.
 */
export const getEvents = <ThrowOnError extends boolean = false>(
  options: Options<GetEventsData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetEventsResponses, unknown, ThrowOnError>({
    querySerializer: { parameters: { events: { array: { explode: false } } } },
    requestValidator: async (data) => await zGetEventsData.parseAsync(data),
    responseValidator: async (data) => await zGetEventsResponse.parseAsync(data),
    security: [
      {
        in: 'query',
        name: 'apikey',
        type: 'apiKey',
      },
    ],
    url: '/sse',
    ...options,
  })

/**
 * Get the current server time.
 *
 * This endpoint provides the current server time, necessary for calculating the client-server offset (cs_offset). This offset is crucial for estimating the server time on the client side (Tcest).
 *
 * **Calculating Client-Server Offset (cs_offset)**
 *
 * 1. **Sample Collection**: Obtain N samples of server time (Ts) from the endpoint. More samples improve accuracy but increase estimation time. A good starting point is 30 samples.
 * 2. **Round-Trip Delay (RTD) Measurement**: For each sample, record the send time (Tsend) and receive time (Treceive). Calculate RTD as Treceive - Tsend.
 * 3. **Server Time Estimation (Ts_est)**: Estimate the server time at response receipt by adding half of the RTD to the server time (Ts). Formula: Ts_est = Ts + RTD/2.
 * 4. **Offset Calculation**: Determine the offset between Ts_est and client time (Tc) at response receipt. Since Tc equals Treceive, the offset is Ts_est - Treceive.
 * 5. **Aggregate Offset Update**: Update the aggregated offset value (offset_agg) by adding the new offset. Formula: offset_agg = offset_agg + offset.
 * 6. **Average Offset (cs_offset)**: After all samples are processed, calculate the average offset by dividing offset_agg by the number of samples (X). Formula: cs_offset = offset_agg / X.
 *
 * This method provides a reliable estimate of the client-server offset (cs_offset).
 *
 * Typically, cs_offset is calculated once and used for future Tcest calculations. However, if synchronization issues arise (due to network changes, clock drift, etc.), recalculating cs_offset may be beneficial.
 *
 * **Calculating Client-Side Estimated Server Time (Tcest)**
 *
 * The Tcest value, required for certain API endpoints (e.g., /hssp/play), is calculated as follows:
 *
 * Tcest = Tc + cs_offset
 *
 * where Tc is the current client time and cs_offset is the pre-calculated client-server offset.
 *
 */
export const getServerTime = <ThrowOnError extends boolean = false>(
  options?: Options<GetServerTimeData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetServerTimeResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetServerTimeData.parseAsync(data),
    responseValidator: async (data) => await zGetServerTimeResponse.parseAsync(data),
    url: '/servertime',
    ...options,
  })

/**
 * Device message statistics.
 *
 * The device message statistics provides information about the device message traffic.
 */
export const getStatistics = <ThrowOnError extends boolean = false>(
  options: Options<GetStatisticsData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetStatisticsResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetStatisticsData.parseAsync(data),
    responseValidator: async (data) => await zGetStatisticsResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/statistics',
    ...options,
  })

/**
 * Get the device capabilities.
 *
 * Get the device capabilities.
 */
export const getDeviceCapabilities = <ThrowOnError extends boolean = false>(
  options: Options<GetDeviceCapabilitiesData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetDeviceCapabilitiesResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetDeviceCapabilitiesData.parseAsync(data),
    responseValidator: async (data) => await zGetDeviceCapabilitiesResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/capabilities',
    ...options,
  })

/**
 * Get the device session IDs.
 *
 * Get the device's session IDs.
 */
export const getDeviceSessionIds = <ThrowOnError extends boolean = false>(
  options: Options<GetDeviceSessionIdsData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetDeviceSessionIdsResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetDeviceSessionIdsData.parseAsync(data),
    responseValidator: async (data) => await zGetDeviceSessionIdsResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/sids',
    ...options,
  })

/**
 * Send a XAVA message to the device.
 *
 * Sets the next absolute position (xa) of the device, and the absolute velocity (va) the device should use to reach the position.
 *
 * See the request body schema definition for details.<br><br>See <a href="https://links.handyfeeling.com/docs-api-handy-rest-v3-hdsp">Handy Direct Streaming Protocol (HDSP)</a> for additional information about the HDSP protocol and code samples.
 *
 */
export const sendXava = <ThrowOnError extends boolean = false>(
  options: Options<SendXavaData, ThrowOnError>,
) =>
  (options.client ?? client).put<SendXavaResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zSendXavaData.parseAsync(data),
    responseValidator: async (data) => await zSendXavaResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/hdsp/xava',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Send a XAVP message to the device.
 *
 * Sets the next absolute position (xa) of the device, and the percent velocity (vp) the device should use to reach the position.
 *
 * See the request schema definition for more information.
 *
 * See <a href="">Notion</a> for additional information and code samples.
 *
 */
export const sendXavp = <ThrowOnError extends boolean = false>(
  options: Options<SendXavpData, ThrowOnError>,
) =>
  (options.client ?? client).put<SendXavpResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zSendXavpData.parseAsync(data),
    responseValidator: async (data) => await zSendXavpResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/hdsp/xavp',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Send a XPVA message to the device.
 *
 * Sets the next percent position (xp) of the device, and the absolute velocity (va) the device should use to reach the position.
 *
 * See the request schema definition for more information.
 *
 * See <a href="">Notion</a> for additional information and code samples.
 *
 */
export const sendXpva = <ThrowOnError extends boolean = false>(
  options: Options<SendXpvaData, ThrowOnError>,
) =>
  (options.client ?? client).put<SendXpvaResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zSendXpvaData.parseAsync(data),
    responseValidator: async (data) => await zSendXpvaResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/hdsp/xpva',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Send a XPVP message to the device.
 *
 * Sets the next percent position (xp) of the device, and the percent velocity (vp) the device should use to reach the position.
 *
 * See the request schema definition for more information
 *
 * See <a href="">Notion</a> for additional information and code samples.
 *
 */
export const sendXpvp = <ThrowOnError extends boolean = false>(
  options: Options<SendXpvpData, ThrowOnError>,
) =>
  (options.client ?? client).put<SendXpvpResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zSendXpvpData.parseAsync(data),
    responseValidator: async (data) => await zSendXpvpResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/hdsp/xpvp',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Send a XAT message to the device.
 *
 * Sets the next absolute position (xa) of the device, and the time (t) the device should use to reach the position.
 *
 * See the request schema definition for more information.
 *
 * See <a href="">Notion</a> for additional information and code samples.
 *
 */
export const sendXat = <ThrowOnError extends boolean = false>(
  options: Options<SendXatData, ThrowOnError>,
) =>
  (options.client ?? client).put<SendXatResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zSendXatData.parseAsync(data),
    responseValidator: async (data) => await zSendXatResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/hdsp/xat',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Send a XAT message to the device.
 *
 * Sets the next percent position (xp) of the device, and the time (t) the device should use to reach the position.
 *
 * See the request schema definition for more information.
 *
 * See <a href="">Notion</a> for additional information and code samples.
 *
 */
export const sendXpt = <ThrowOnError extends boolean = false>(
  options: Options<SendXptData, ThrowOnError>,
) =>
  (options.client ?? client).put<SendXptResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zSendXptData.parseAsync(data),
    responseValidator: async (data) => await zSendXptResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/hdsp/xpt',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Get the current HSSP state of the device.
 *
 * Get the current HSSP state of the device.
 *
 * See the request body schema definition for details.<br><br>See <a href="https://links.handyfeeling.com/docs-api-handy-rest-v3-hssp">Handy Synchronized Script Protocol (HSSP)</a> for additional information about the HSSP protocol and code samples.
 *
 */
export const getHsspState = <ThrowOnError extends boolean = false>(
  options: Options<GetHsspStateData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetHsspStateResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetHsspStateData.parseAsync(data),
    responseValidator: async (data) => await zGetHsspStateResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/hssp/state',
    ...options,
  })

/**
 * Setup the HSSP protocol.
 *
 * Setup the HSSP protocol.
 *
 * See the request body schema definition for details.<br><br>See <a href="https://links.handyfeeling.com/docs-api-handy-rest-v3-hssp">Handy Synchronized Script Protocol (HSSP)</a> for additional information about the HSSP protocol and code samples.
 *
 * If you can't host your own scripts, you can use our script hosting service to get a temporary script download URL:
 *
 * See the [Hosting API](https://www.handyfeeling.com/api/hosting/v2/docs/) or the [Hosting API docs](https://ohdoki.notion.site/Hosting-API-v2-814e654381e74f2faebe2ebd908a878f)
 *
 */
export const hsspSetup = <ThrowOnError extends boolean = false>(
  options: Options<HsspSetupData, ThrowOnError>,
) =>
  (options.client ?? client).put<HsspSetupResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zHsspSetupData.parseAsync(data),
    responseValidator: async (data) => await zHsspSetupResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/hssp/setup',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Start the HSSP playback.
 *
 * Start the HSSP playback.
 *
 * See the request body schema definition for details.<br><br>See <a href="https://links.handyfeeling.com/docs-api-handy-rest-v3-hssp">Handy Synchronized Script Protocol (HSSP)</a> for additional information about the HSSP protocol and code samples.
 *
 */
export const hsspPlay = <ThrowOnError extends boolean = false>(
  options: Options<HsspPlayData, ThrowOnError>,
) =>
  (options.client ?? client).put<HsspPlayResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zHsspPlayData.parseAsync(data),
    responseValidator: async (data) => await zHsspPlayResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/hssp/play',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Stop the HSSP playback.
 *
 * Stop the HSSP playback.
 *
 * See the request body schema definition for details.<br><br>See <a href="https://links.handyfeeling.com/docs-api-handy-rest-v3-hssp">Handy Synchronized Script Protocol (HSSP)</a> for additional information about the HSSP protocol and code samples.
 *
 */
export const hsspStop = <ThrowOnError extends boolean = false>(
  options: Options<HsspStopData, ThrowOnError>,
) =>
  (options.client ?? client).put<HsspStopResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zHsspStopData.parseAsync(data),
    responseValidator: async (data) => await zHsspStopResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/hssp/stop',
    ...options,
  })

/**
 * Pause the HSSP playback.
 *
 * Pause the HSSP playback.
 *
 * Pause will pause the playback, but keep the current position. A subsequent resume command will continue playback from the paused position or from the current 'live' script position/time, depending on the resume `pickUp` flag.
 *
 * See the request body schema definition for details.<br><br>See <a href="https://links.handyfeeling.com/docs-api-handy-rest-v3-hsp">Handy Streaming Protocol (HSP)</a> for additional information about the HSP protocol and code samples.
 *
 */
export const hsspPause = <ThrowOnError extends boolean = false>(
  options: Options<HsspPauseData, ThrowOnError>,
) =>
  (options.client ?? client).put<HsspPauseResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zHsspPauseData.parseAsync(data),
    responseValidator: async (data) => await zHsspPauseResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/hssp/pause',
    ...options,
  })

/**
 * Resume the HSSP playback.
 *
 * Resume the HSSP playback.
 *
 * Depending on the `pickUp` parameter, resume will either continue from the paused position (`pickUp` = false) or jump to the current 'live' position/time of the script (`pickUp` = true).
 *
 * See the request body schema definition for details.<br><br>See <a href="https://links.handyfeeling.com/docs-api-handy-rest-v3-hsp">Handy Streaming Protocol (HSP)</a> for additional information about the HSP protocol and code samples.
 *
 */
export const hsspResume = <ThrowOnError extends boolean = false>(
  options: Options<HsspResumeData, ThrowOnError>,
) =>
  (options.client ?? client).put<HsspResumeResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zHsspResumeData.parseAsync(data),
    responseValidator: async (data) => await zHsspResumeResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/hssp/resume',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Adjust the stream synchronization.
 *
 * Adjust the stream playtime using the provided current time sample from the external source and filter.
 *
 * This can improve the synchronization between the device and the external source when the current time samples have some variable inaccuracies.
 *
 * See the request body schema definition for details.<br><br>See <a href="https://links.handyfeeling.com/docs-api-handy-rest-v3-hssp">Handy Synchronized Script Protocol (HSSP)</a> for additional information about the HSSP protocol and code samples.
 *
 */
export const setHsspTime = <ThrowOnError extends boolean = false>(
  options: Options<SetHsspTimeData, ThrowOnError>,
) =>
  (options.client ?? client).put<SetHsspTimeResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zSetHsspTimeData.parseAsync(data),
    responseValidator: async (data) => await zSetHsspTimeResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/hssp/synctime',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Setup a new HSP session on the device.
 *
 * Setup initializes a new HSP session on the device. This ensures both the device and server are properly prepared, clearing any existing HSP session state.
 *
 * If the device is already in an HSP session and no setup command is issued, all HSP commands will modify the existing session, which may lead to unexpected behavior.
 *
 * The `stream_id` is an optional session identifier. If it changes during a HSP session, it indicates that a new session has been initiated by a client. If no `stream_id` is provided, one will be generated and returned in the setup response.
 *
 * See the request body schema definition for details.<br><br>See <a href="https://links.handyfeeling.com/docs-api-handy-rest-v3-hsp">Handy Streaming Protocol (HSP)</a> for additional information about the HSP protocol and code samples.
 *
 */
export const hspSetup = <ThrowOnError extends boolean = false>(
  options: Options<HspSetupData, ThrowOnError>,
) =>
  (options.client ?? client).put<HspSetupResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zHspSetupData.parseAsync(data),
    responseValidator: async (data) => await zHspSetupResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/hsp/setup',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Flush the HSP buffer.
 *
 * Flush will remove all existing points from the device point buffer.
 *
 * See the request body schema definition for details.<br><br>See <a href="https://links.handyfeeling.com/docs-api-handy-rest-v3-hsp">Handy Streaming Protocol (HSP)</a> for additional information about the HSP protocol and code samples.
 *
 */
export const hspFlush = <ThrowOnError extends boolean = false>(
  options: Options<HspFlushData, ThrowOnError>,
) =>
  (options.client ?? client).put<HspFlushResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zHspFlushData.parseAsync(data),
    responseValidator: async (data) => await zHspFlushResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/hsp/flush',
    ...options,
  })

/**
 * Add points to the device HSP point buffer.
 *
 * You can add up to 100 points to the device's point buffer in a single command.
 *
 * If the buffer is full, adding N points will remove the first N points to make room for the new ones.
 *
 * The `flush` flag can be used to remove all existing points from the buffer before adding the new points.
 *
 * The `tail_point_threshold` parameter can be used to update the tail point stream index threshold after the points have been added.
 *
 * See the request body schema definition for details.<br><br>See <a href="https://links.handyfeeling.com/docs-api-handy-rest-v3-hsp">Handy Streaming Protocol (HSP)</a> for additional information about the HSP protocol and code samples.
 *
 */
export const hspAdd = <ThrowOnError extends boolean = false>(
  options: Options<HspAddData, ThrowOnError>,
) =>
  (options.client ?? client).put<HspAddResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zHspAddData.parseAsync(data),
    responseValidator: async (data) => await zHspAddResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/hsp/add',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Start the HSP playback.
 *
 * Start the HSP playback.
 *
 * An optional add points command can be embedded in the play command. The add command (if present) will be executed before the playback starts.
 *
 * See the request body schema definition for details.<br><br>See <a href="https://links.handyfeeling.com/docs-api-handy-rest-v3-hsp">Handy Streaming Protocol (HSP)</a> for additional information about the HSP protocol and code samples.
 *
 */
export const hspPlay = <ThrowOnError extends boolean = false>(
  options: Options<HspPlayData, ThrowOnError>,
) =>
  (options.client ?? client).put<HspPlayResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zHspPlayData.parseAsync(data),
    responseValidator: async (data) => await zHspPlayResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/hsp/play',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Stop the HSP playback.
 *
 * Stop the HSP playback.
 *
 * See the request body schema definition for details.<br><br>See <a href="https://links.handyfeeling.com/docs-api-handy-rest-v3-hsp">Handy Streaming Protocol (HSP)</a> for additional information about the HSP protocol and code samples.
 *
 */
export const hspStop = <ThrowOnError extends boolean = false>(
  options: Options<HspStopData, ThrowOnError>,
) =>
  (options.client ?? client).put<HspStopResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zHspStopData.parseAsync(data),
    responseValidator: async (data) => await zHspStopResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/hsp/stop',
    ...options,
  })

/**
 * Get the current HSP state of the device.
 *
 * Get the current HSP state of the device.
 *
 * See the request body schema definition for details.<br><br>See <a href="https://links.handyfeeling.com/docs-api-handy-rest-v3-hsp">Handy Streaming Protocol (HSP)</a> for additional information about the HSP protocol and code samples.
 *
 */
export const getHspState = <ThrowOnError extends boolean = false>(
  options: Options<GetHspStateData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetHspStateResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetHspStateData.parseAsync(data),
    responseValidator: async (data) => await zGetHspStateResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/hsp/state',
    ...options,
  })

/**
 * Set the HSP tail point stream index threshold.
 *
 * Set the HSP tail point stream index threshold.
 *
 * See the request body schema definition for details.<br><br>See <a href="https://links.handyfeeling.com/docs-api-handy-rest-v3-hsp">Handy Streaming Protocol (HSP)</a> for additional information about the HSP protocol and code samples.
 *
 */
export const setHspThreshold = <ThrowOnError extends boolean = false>(
  options: Options<SetHspThresholdData, ThrowOnError>,
) =>
  (options.client ?? client).put<SetHspThresholdResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zSetHspThresholdData.parseAsync(data),
    responseValidator: async (data) => await zSetHspThresholdResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/hsp/threshold',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Pause the HSP playback.
 *
 * Pause the HSP playback.
 *
 * Pause will pause the playback, but keep the current position. A subsequent resume command will continue playback from the paused position or from the current 'live' stream position, depending on the resume command parameters.
 *
 * See the request body schema definition for details.<br><br>See <a href="https://links.handyfeeling.com/docs-api-handy-rest-v3-hsp">Handy Streaming Protocol (HSP)</a> for additional information about the HSP protocol and code samples.
 *
 */
export const hspPause = <ThrowOnError extends boolean = false>(
  options: Options<HspPauseData, ThrowOnError>,
) =>
  (options.client ?? client).put<HspPauseResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zHspPauseData.parseAsync(data),
    responseValidator: async (data) => await zHspPauseResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/hsp/pause',
    ...options,
  })

/**
 * Resume the HSP playback.
 *
 * Resume the HSP playback.
 *
 * Depending on the `pick_up` parameter, resume will either continue from the paused position (`pick_up` = false) or jump to the current 'live' position of the stream (`pick_up` = true).
 *
 * See the request body schema definition for details.<br><br>See <a href="https://links.handyfeeling.com/docs-api-handy-rest-v3-hsp">Handy Streaming Protocol (HSP)</a> for additional information about the HSP protocol and code samples.
 *
 */
export const hspResume = <ThrowOnError extends boolean = false>(
  options: Options<HspResumeData, ThrowOnError>,
) =>
  (options.client ?? client).put<HspResumeResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zHspResumeData.parseAsync(data),
    responseValidator: async (data) => await zHspResumeResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/hsp/resume',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Set the HSP pause-on-starving flag.
 *
 * Set the HSP pause-on-starving flag.
 *
 * See the request body schema definition for details.<br><br>See <a href="https://links.handyfeeling.com/docs-api-handy-rest-v3-hsp">Handy Streaming Protocol (HSP)</a> for additional information about the HSP protocol and code samples.
 *
 */
export const setHspPauseOnStarving = <ThrowOnError extends boolean = false>(
  options: Options<SetHspPauseOnStarvingData, ThrowOnError>,
) =>
  (options.client ?? client).put<SetHspPauseOnStarvingResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zSetHspPauseOnStarvingData.parseAsync(data),
    responseValidator: async (data) => await zSetHspPauseOnStarvingResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/hsp/pause/onstarving',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Adjust the stream synchronization.
 *
 * Adjust the stream playtime using the provided current time sample from the external source and filter.
 *
 * This can improve the synchronization between the device and the external source when the current time samples have some variable inaccuracies.
 *
 * See the request body schema definition for details.<br><br>See <a href="https://links.handyfeeling.com/docs-api-handy-rest-v3-hsp">Handy Streaming Protocol (HSP)</a> for additional information about the HSP protocol and code samples.
 *
 */
export const setHspTime = <ThrowOnError extends boolean = false>(
  options: Options<SetHspTimeData, ThrowOnError>,
) =>
  (options.client ?? client).put<SetHspTimeResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zSetHspTimeData.parseAsync(data),
    responseValidator: async (data) => await zSetHspTimeResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/hsp/synctime',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Set the HSP loop flag.
 *
 * Set the HSP loop flag.
 *
 * See the request body schema definition for details.<br><br>See <a href="https://links.handyfeeling.com/docs-api-handy-rest-v3-hsp">Handy Streaming Protocol (HSP)</a> for additional information about the HSP protocol and code samples.
 *
 */
export const setHspLoop = <ThrowOnError extends boolean = false>(
  options: Options<SetHspLoopData, ThrowOnError>,
) =>
  (options.client ?? client).put<SetHspLoopResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zSetHspLoopData.parseAsync(data),
    responseValidator: async (data) => await zSetHspLoopResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/hsp/loop',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Set the HSP playback rate.
 *
 * Set the HSP playback rate.
 *
 * See the request body schema definition for details.<br><br>See <a href="https://links.handyfeeling.com/docs-api-handy-rest-v3-hsp">Handy Streaming Protocol (HSP)</a> for additional information about the HSP protocol and code samples.
 *
 */
export const setHspPaybackRate = <ThrowOnError extends boolean = false>(
  options: Options<SetHspPaybackRateData, ThrowOnError>,
) =>
  (options.client ?? client).put<SetHspPaybackRateResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zSetHspPaybackRateData.parseAsync(data),
    responseValidator: async (data) => await zSetHspPaybackRateResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/hsp/playbackrate',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Get the current device time information.
 *
 * Get the current device time information.
 */
export const getDeviceTimeInfo = <ThrowOnError extends boolean = false>(
  options: Options<GetDeviceTimeInfoData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetDeviceTimeInfoResponses, GetDeviceTimeInfoErrors, ThrowOnError>(
    {
      requestValidator: async (data) => await zGetDeviceTimeInfoData.parseAsync(data),
      responseValidator: async (data) => await zGetDeviceTimeInfoResponse.parseAsync(data),
      security: [
        { name: 'X-Api-Key', type: 'apiKey' },
        { scheme: 'bearer', type: 'http' },
      ],
      url: '/hstp/info',
      ...options,
    },
  )

/**
 * Initiate a server-device clock synchronization.
 *
 * Initiate a server-device clock synchronization.
 */
export const clockSync = <ThrowOnError extends boolean = false>(
  options: Options<ClockSyncData, ThrowOnError>,
) =>
  (options.client ?? client).get<ClockSyncResponses, ClockSyncErrors, ThrowOnError>({
    requestValidator: async (data) => await zClockSyncData.parseAsync(data),
    responseValidator: async (data) => await zClockSyncResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/hstp/clocksync',
    ...options,
  })

/**
 * Get the device time offset.
 *
 * Get the user adjusted device time offset.
 */
export const getOffset = <ThrowOnError extends boolean = false>(
  options: Options<GetOffsetData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetOffsetResponses, GetOffsetErrors, ThrowOnError>({
    requestValidator: async (data) => await zGetOffsetData.parseAsync(data),
    responseValidator: async (data) => await zGetOffsetResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/hstp/offset',
    ...options,
  })

/**
 * Set the user adjusted device time offset.
 *
 * Set the user adjusted device time offset.
 */
export const setOffset = <ThrowOnError extends boolean = false>(
  options: Options<SetOffsetData, ThrowOnError>,
) =>
  (options.client ?? client).put<SetOffsetResponses, SetOffsetErrors, ThrowOnError>({
    requestValidator: async (data) => await zSetOffsetData.parseAsync(data),
    responseValidator: async (data) => await zSetOffsetResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/hstp/offset',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Get the current HVP state of the device.
 *
 * Get the current HVP state of the device.
 *
 * See the request body schema definition for details.<br><br>See <a href="https://links.handyfeeling.com/docs-api-handy-rest-v3-hvp">Handy Vibration Protocol (HVP)</a> for additional information about the HVP protocol and code samples.
 *
 */
export const getHvpState = <ThrowOnError extends boolean = false>(
  options: Options<GetHvpStateData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetHvpStateResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetHvpStateData.parseAsync(data),
    responseValidator: async (data) => await zGetHvpStateResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/hvp/state',
    ...options,
  })

/**
 * Set the current HVP state of the device.
 *
 * Set the HVP state of the device.
 *
 * See the request body schema definition for details.<br><br>See <a href="https://links.handyfeeling.com/docs-api-handy-rest-v3-hvp">Handy Vibration Protocol (HVP)</a> for additional information about the HVP protocol and code samples.
 *
 */
export const setHvpState = <ThrowOnError extends boolean = false>(
  options: Options<SetHvpStateData, ThrowOnError>,
) =>
  (options.client ?? client).put<SetHvpStateResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zSetHvpStateData.parseAsync(data),
    responseValidator: async (data) => await zSetHvpStateResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/hvp/state',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Start the HVP playback.
 *
 * Start the HVP playback.
 *
 * See the request body schema definition for details.<br><br>See <a href="https://links.handyfeeling.com/docs-api-handy-rest-v3-hvp">Handy Vibration Protocol (HVP)</a> for additional information about the HVP protocol and code samples.
 *
 */
export const hvpStart = <ThrowOnError extends boolean = false>(
  options: Options<HvpStartData, ThrowOnError>,
) =>
  (options.client ?? client).put<HvpStartResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zHvpStartData.parseAsync(data),
    responseValidator: async (data) => await zHvpStartResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/hvp/start',
    ...options,
  })

/**
 * Stop the HVP playback.
 *
 * Stop the HVP playback.
 *
 * See the request body schema definition for details.<br><br>See <a href="https://links.handyfeeling.com/docs-api-handy-rest-v3-hvp">Handy Vibration Protocol (HVP)</a> for additional information about the HVP protocol and code samples.
 *
 */
export const hvpStop = <ThrowOnError extends boolean = false>(
  options: Options<HvpStopData, ThrowOnError>,
) =>
  (options.client ?? client).put<HvpStopResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zHvpStopData.parseAsync(data),
    responseValidator: async (data) => await zHvpStopResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/hvp/stop',
    ...options,
  })

/**
 * Get the current state of the device slider.
 *
 * Get the current state of the device slider.
 *
 */
export const getSlideState = <ThrowOnError extends boolean = false>(
  options: Options<GetSlideStateData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetSlideStateResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetSlideStateData.parseAsync(data),
    responseValidator: async (data) => await zGetSlideStateResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/slider/state',
    ...options,
  })

/**
 * Get the stroke settings of the device slider.
 *
 * Get the minimum and maximum allowed relative slider position of the device.
 */
export const getStroke = <ThrowOnError extends boolean = false>(
  options: Options<GetStrokeData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetStrokeResponses, GetStrokeErrors, ThrowOnError>({
    requestValidator: async (data) => await zGetStrokeData.parseAsync(data),
    responseValidator: async (data) => await zGetStrokeResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/slider/stroke',
    ...options,
  })

/**
 * Set the stroke settings of the device slider.
 *
 * Set the minimum and/or maximum allowed relative slider position of the device.
 * The slider will not move outside the specified stroke zone.
 *
 */
export const setStroke = <ThrowOnError extends boolean = false>(
  options: Options<SetStrokeData, ThrowOnError>,
) =>
  (options.client ?? client).put<SetStrokeResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zSetStrokeData.parseAsync(data),
    responseValidator: async (data) => await zSetStrokeResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/slider/stroke',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Setup the stream protocol.
 *
 * Setup the stream protocol to play a stream.
 *
 * See the request body schema definition for details.<br><br>See <a href="https://links.handyfeeling.com/docs-api-handy-rest-v3-stream">Stream Protocol (STREAM)</a> for additional information about the STREAM protocol and code samples.
 *
 */
export const setupStream = <ThrowOnError extends boolean = false>(
  options: Options<SetupStreamData, ThrowOnError>,
) =>
  (options.client ?? client).put<SetupStreamResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zSetupStreamData.parseAsync(data),
    responseValidator: async (data) => await zSetupStreamResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/stream/setup',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Start the stream playback.
 *
 * Start the stream playback.
 *
 * See the request body schema definition for details.<br><br>See <a href="https://links.handyfeeling.com/docs-api-handy-rest-v3-stream">Stream Protocol (STREAM)</a> for additional information about the STREAM protocol and code samples.
 *
 */
export const streamPlay = <ThrowOnError extends boolean = false>(
  options: Options<StreamPlayData, ThrowOnError>,
) =>
  (options.client ?? client).put<StreamPlayResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zStreamPlayData.parseAsync(data),
    responseValidator: async (data) => await zStreamPlayResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/stream/play',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Stop the stream playback.
 *
 * Stop the stream playback.
 *
 * See the request body schema definition for details.<br><br>See <a href="https://links.handyfeeling.com/docs-api-handy-rest-v3-stream">Stream Protocol (STREAM)</a> for additional information about the STREAM protocol and code samples.
 *
 */
export const streamStop = <ThrowOnError extends boolean = false>(
  options: Options<StreamStopData, ThrowOnError>,
) =>
  (options.client ?? client).put<StreamStopResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zStreamStopData.parseAsync(data),
    responseValidator: async (data) => await zStreamStopResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/stream/stop',
    ...options,
  })

/**
 * Get the current stream state of the device.
 *
 * Get the current stream state of the device.
 *
 * See the request body schema definition for details.<br><br>See <a href="https://links.handyfeeling.com/docs-api-handy-rest-v3-stream">Stream Protocol (STREAM)</a> for additional information about the STREAM protocol and code samples.
 *
 */
export const getStreamState = <ThrowOnError extends boolean = false>(
  options: Options<GetStreamStateData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetStreamStateResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetStreamStateData.parseAsync(data),
    responseValidator: async (data) => await zGetStreamStateResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/stream/state',
    ...options,
  })

/**
 * Adjust the stream synchronization.
 *
 * Adjust the stream playtime using the provided current time sample from the external source and filter.
 *
 * This can improve the synchronization between the device and the external source when the current time samples have some variable inaccuracies.
 *
 * See the request body schema definition for details.<br><br>See <a href="https://links.handyfeeling.com/docs-api-handy-rest-v3-stream">Stream Protocol (STREAM)</a> for additional information about the STREAM protocol and code samples.
 *
 */
export const setStreamTime = <ThrowOnError extends boolean = false>(
  options: Options<SetStreamTimeData, ThrowOnError>,
) =>
  (options.client ?? client).put<SetStreamTimeResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zSetStreamTimeData.parseAsync(data),
    responseValidator: async (data) => await zSetStreamTimeResponse.parseAsync(data),
    security: [
      { name: 'X-Api-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
    ],
    url: '/stream/synctime',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
