// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'https://www.handyfeeling.com/api/handy-rest/v3' | (string & {})
}

/**
 * Generic error response
 */
export type GenericError = {
  /**
   * The error name.
   */
  name: string
  /**
   * The error message.
   */
  message?: string
  /**
   * The error code.
   */
  code: number
  /**
   * Additional error data.
   */
  data?: {
    [key: string]: unknown
  }
}

/**
 * Auth token response
 */
export type AuthTokenResponse = {
  result?: ClientToken
  error?: GenericError
}

/**
 * Client token
 */
export type ClientToken = {
  /**
   * The token reference.
   */
  token_ref: string
  created_at: DateTime
  expires_at: DateTime
  /**
   * The issued authentication token.
   */
  token: string
  /**
   * The url to renew the token.
   */
  renew: string
}

/**
 * Possible device modes.
 * <br><br>
 * - 0: hamp
 * - 1: hssp
 * - 2: hdsp
 * - 3: maintenance
 * - 4: hsp
 * - 5: ota
 * - 6: button
 * - 7: idle
 * - 8: vibrate
 * - 9: hrpp
 *
 */
export type DeviceModeValue = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8

/**
 * Device mode response
 */
export type DeviceMode = {
  mode: DeviceModeValue
  /**
   * The mode session id. Changes every time the mode changes.
   */
  mode_session_id?: number
}

export type Timestamp = number

export type DateTime = string

export type ConnectionKey = string

/**
 * Device environment.
 * <br><br>
 * - 0: production
 * - 1: staging
 * - 2: development
 *
 */
export type DeviceEnvironment = 0 | 1 | 2

/**
 * Connection mode.
 * <br><br>
 * - 0: none
 * - 1: WIFI
 * - 2: BLE
 * - 3: WIFI_BLE
 * - 4: OFFLINE
 * - 5: LEGACY_BLE
 *
 */
export type ConnectionMode = 0 | 1 | 2 | 3 | 4 | 5

export type ChannelReference = string

/**
 * The event type
 */
export type SseEventType =
  | 'battery_changed'
  | 'ble_status_changed'
  | 'button_event'
  | 'device_clock_synchronized'
  | 'device_connected'
  | 'device_disconnected'
  | 'device_error'
  | 'device_status'
  | 'hamp_state_changed'
  | 'hrpp_state_changed'
  | 'hdsp_state_changed'
  | 'hsp_looping'
  | 'hsp_starving'
  | 'hsp_state_changed'
  | 'hsp_threshold_reached'
  | 'stream_end_reached'
  | 'hvp_state_changed'
  | 'low_memory_error'
  | 'low_memory_warning'
  | 'mode_changed'
  | 'ota_progress'
  | 'slider_blocked'
  | 'slider_unblocked'
  | 'stroke_changed'
  | 'temp_high'
  | 'temp_ok'
  | 'wifi_scan_complete'
  | 'wifi_status'
  | 'wifi_status_changed'

/**
 * SSE device data
 */
export type SseEventData = {
  connection_key: ConnectionKey
  /**
   * The device specific event data
   */
  data?:
    | DeviceInfo
    | DeviceDisconnected
    | ButtonEvent
    | BleStatus
    | WifiStatus
    | WifiScanComplete
    | LowMemoryWarning
    | LowMemoryError
    | BatteryStatus
    | StrokeStatus
    | OtaProgress
    | HdspState
    | HampState
    | HspState
    | HvpState
    | ErrorData
    | DeviceStatus
    | DeviceMode
    | DeviceTimeInfo
}

/**
 * SSE event
 */
export type SseEvent = {
  /**
   * The event id
   */
  id: string
  type: SseEventType
  data: SseEventData
}

/**
 * The current HDSP state.<br>
 * Possible values:
 * - 0: stopped
 * - 1: moving
 * - 2: point reached
 *
 */
export type HdspStateValue = 0 | 1 | 2

/**
 * HDSP state
 */
export type HdspState = {
  state: HdspStateValue
}

/**
 * Device status
 */
export type DeviceStatus = {
  /**
   * If the device is connected
   */
  connected: boolean
  info?: DeviceInfo
}

/**
 * HVP state
 */
export type HvpState = {
  /**
   * Flag to indicate if vibration is enabled.
   */
  enabled: boolean
  /**
   * The vibration amplitude. 0-1 (0-100%, percent of valid output range). For LRA, ERM and sliders with vibration adapter
   */
  amplitude: number
  /**
   * The vibration frequency. 0-10000 (Hz) For LRA only.
   */
  frequency: number
  /**
   * The vibration position (mm). Where on the slider should the vibration be. Only applies to devices with a slider with vibration adapter.
   */
  position: number
}

/**
 * Error data
 */
export type ErrorData = {
  /**
   * The error code
   */
  code: number
  /**
   * The error message
   */
  message: string
}

/**
 * The button pressed.<br>
 * Possible values:
 * - 0: power
 * - 1: up
 * - 2: left
 * - 3: right
 * - 4: down
 * - 5: Wifi
 *
 */
export type ButtonValue = 0 | 1 | 2 | 3 | 4 | 5

/**
 * The button press type.<br>
 * Possible values:
 * - 0: pressed
 * - 1: released
 * - 2: short press
 * - 3: long press start
 * - 4: long press step
 * - 5: long press end
 *
 */
export type ButtonEventType = 0 | 1 | 2 | 3 | 4 | 5

/**
 * Button event data
 */
export type ButtonEvent = {
  button: ButtonValue
  event: ButtonEventType
}

/**
 * OTA status
 */
export type OtaProgress = {
  /**
   * Ota flag to indicate if the OTA is done.
   */
  done: boolean
  /**
   * The OTA progress.
   */
  progress: number
  /**
   * Ota flag to indicate if the OTA failed.
   */
  failed: boolean
}

/**
 * Stroke status
 */
export type StrokeStatus = {
  /**
   * The relative minimum slider position.
   */
  min: number
  /**
   * The relative maximum slider position.
   */
  max: number
  /**
   * The absolute minimum slider position (in millimeter).
   */
  min_absolute: number
  /**
   * The absolute maximum slider position (in millimeter).
   */
  max_absolute: number
}

/**
 * Battery status
 */
export type BatteryStatus = {
  /**
   * The battery level
   */
  level: number
  /**
   * The charging status
   */
  charger_connected: boolean
  /**
   * The charging status
   */
  charging_complete: boolean
  /**
   * The USB voltage (in V)
   */
  usb_voltage: number
  /**
   * The battery voltage (in V)
   */
  battery_voltage: number
  /**
   * The USB ADC value (0-4095)
   */
  usb_adc_value: number
  /**
   * The battery ADC value (0-4095)
   */
  battery_adc_value: number
}

/**
 * Low memory warning event data
 */
export type LowMemoryWarning = {
  /**
   * The available heap size
   */
  available_heap: number
  /**
   * The size of the largest free block
   */
  larges_free_block: number
}

/**
 * Low memory error event data
 */
export type LowMemoryError = {
  /**
   * The available heap size
   */
  available_heap: number
  /**
   * The size of the largest free block
   */
  larges_free_block: number
  /**
   * The size of the last discarded message
   */
  discarded_msg_size: number
}

/**
 * WIFI scan complete event data
 */
export type WifiScanComplete = {
  /**
   * The number of networks found
   */
  nr_of_networks: number
}

/**
 * The WIFI state.<br>
 * Possible values:
 * - 0: Disconnected
 * - 1: Connected
 * - 2: Connecting
 * - 3: Reconneting
 * - 4: Failed to connect
 * - 5: Disconnecting
 *
 */
export type WifiStateValue = 0 | 1 | 2 | 3 | 4 | 5

/**
 * WIFI status
 */
export type WifiStatus = {
  /**
   * Flag to indicate if the socket is connected.
   */
  socket_connected: boolean
  state: WifiStateValue
}

/**
 * The BLE status.<br>
 * Possible values:
 * - 0: Not initialized
 * - 1: Initializing
 * - 2: Advertising
 * - 3: Connected
 *
 */
export type BleStatusValue = 0 | 1 | 2 | 3

/**
 * BLE status
 */
export type BleStatus = {
  status: BleStatusValue
}

/**
 * Device disconnected event data
 */
export type DeviceDisconnected = {
  /**
   * The reason for the disconnection
   */
  reason: string
  /**
   * The device session id
   */
  session_id: string
  /**
   * The disconnect timestamp
   */
  timestamp: string
}

/**
 * Device statistics
 */
export type DeviceStatistics = {
  timestamp: DateTime
  /**
   * Current transit size
   */
  transit_size?: number
  /**
   * Maximum transit size
   */
  max_transit_size?: number
  /**
   * Current buffer size
   */
  buffer_size?: number
  /**
   * Maximum buffer size
   */
  max_buffer_size?: number
  /**
   * The total number of bytes sent to the device
   */
  total_bytes?: number
  /**
   * The total number of messages sent to the device
   */
  total_messages?: number
  /**
   * The total number of bytes dropped
   */
  dropped_bytes?: number
  /**
   * The total number of messages dropped
   */
  dropped_messages?: number
  /**
   * The total number of acknowledged bytes sent to the device
   */
  acked_bytes?: number
  /**
   * The total number of acknowledged messages sent to the device
   */
  acked_messages?: number
}

/**
 * HAMP state
 */
export type HampState = {
  play_state: HampPlayState
  /**
   * The current velocity
   */
  velocity: number
  /**
   * The current direction. True=UP. False=DOWN.
   */
  direction: boolean
}

/**
 * The velocity of the HAMP device. [0-1] 1=100% of max velocity.
 */
export type HampVelocity = number

/**
 * HAMP play state.
 * <br><br>
 * - 0: stopped
 * - 1: playing
 *
 */
export type HampPlayState = 0 | 1

export type HsspSetupUrl = {
  /**
   * The script url.
   */
  url: string
}

export type HsspSetupCsv = {
  /**
   * The script csv data.
   */
  csv: string
}

export type HsspSetupFunscript = {
  /**
   * The funscript actions.
   */
  actions: Array<Action>
}

/**
 * HSP state
 */
export type HspState = {
  play_state: HspPlayState
  /**
   * The current number of points in the HSP buffer
   */
  points: number
  pause_on_starving: PauseOnStarving
  /**
   * The maximum number of points the HSP buffer can hold.
   */
  max_points: number
  /**
   * The current point position being played.
   */
  current_point: number
  /**
   * The current point time being played.
   */
  current_time: number
  /**
   * The current loop state.
   */
  loop: boolean
  /**
   * The current playback rate.
   */
  playback_rate: number
  /**
   * The time of the first point in the HSP buffer.
   */
  first_point_time: number
  /**
   * The time of the last point in the HSP buffer.
   */
  last_point_time: number
  /**
   * The current stream id.
   */
  stream_id: number
  /**
   * The tail point stream index. The absolute stream index of the last point in the HSP buffer relative to the overall stream.
   */
  tail_point_stream_index: number
  /**
   * The tail point stream index threshold. The threshold for when the starving notifications will be sent.
   */
  tail_point_stream_index_threshold: number
}

/**
 * HSSP play state.<br>
 * - 0: Not initialized
 * - 1: playing
 * - 2: stopped
 * - 3: paused
 * - 4: starving
 *
 */
export type HspPlayState = 0 | 1 | 2 | 3 | 4

/**
 * The position of the point. For devices with a slider this is the relative position [0,100] [0=bottom, 100=top] of the slider length.
 */
export type PointPosition = number

/**
 * The timestamp of a point in milliseconds relative to the start time (t=0).
 */
export type PointTime = number

/**
 * Funscript action
 */
export type Action = {
  at: PointTime
  pos: PointPosition
}

/**
 * HSP point
 */
export type Point = {
  t: PointTime
  x: PointPosition
}

/**
 * Slider state
 */
export type SliderState = {
  /**
   * The current relative position [0,1] [0=bottom, 1=top] of the slider.
   */
  position: number
  /**
   * The current absolute position (in mm) of the slider.
   */
  position_absolute: number
  /**
   * The current motor temperature (°C).
   */
  motor_temp: number
  /**
   * The current absolute speed (millimeter/s) of the slider.
   */
  speed_absolute: number
  /**
   * The current motor direction. True for forware, false for backward.
   */
  dir: boolean
  /**
   * The current motor position.
   */
  motor_position: number
  /**
   * ADC value of the motor temperature sensor (0-4095). Available from firmware v4.0.16
   */
  motor_temp_adc_value?: number
}

export type StrokeSettings = {
  /**
   * Relative minimum slider position. A value between 0.0 and 1.0.
   */
  min: number
  /**
   * Relative maximum slider position. A value between 0.0 and 1.0.
   */
  max: number
}

export type HampStrokeSettings = {
  /**
   * Relative minimum slider position (within the current slider settings). A value between 0.0 and 1.0.
   */
  min: number
  /**
   * Relative maximum slider position (within the current slider settings). A value between 0.0 and 1.0.
   */
  max: number
}

export type StrokeSettingsRsp = {
  /**
   * Relative minimum slider position. A value between 0.0 and 1.0.
   */
  min: number
  /**
   * Relative maximum slider position. A value between 0.0 and 1.0.
   */
  max: number
  /**
   * Absolute minimum slider position in millimeter.
   */
  min_absolute: number
  /**
   * Absolute maximum slider position in millimeter.
   */
  max_absolute: number
}

/**
 * Firmware feature flags
 */
export type FirmwareFeatureFlags = 'production' | 'staging' | 'development' | 'other'

export type DeviceInfo = {
  fw_status: FirmwareStatus
  /**
   * Firmware version
   */
  fw_version: string
  fw_feature_flags?: FirmwareFeatureFlags
  /**
   * Hardware model number
   */
  hw_model_no?: number
  /**
   * Hardware model name
   */
  hw_model_name?: string
  /**
   * Hardware model variant
   */
  hw_model_variant?: number
  /**
   * The device session id. This id is unique for each device session. A new session id is assigned each time the device connects to the server.
   */
  session_id: string
}

export type DeviceTimeInfo = {
  /**
   * The current time of the device (time since boot in milliseconds).
   */
  time: number
  /**
   * The clock offset in milliseconds. This is the offset between the server and the device. The clock of the device starts at 0 on every boot.
   */
  clock_offset: number
  /**
   * The round trip delay in milliseconds between the server and the device (observed on the latest clocksync).
   */
  rtd: number
}

/**
 * Firmware status.
 * <br><br>
 * - 0: up-to-date
 * - 1: update-available
 * - 2: update-required
 *
 */
export type FirmwareStatus = 0 | 1 | 2

/**
 * Device settings
 */
export type SliderSettings = {
  /**
   * The start of the slider limit (in mm).
   */
  x_limit_start: number
  /**
   * The end of the slider limit (in mm).
   */
  x_limit_stop: number
  /**
   * The end buffer (in mm). The distance from the end of the stroke where the device will start to slow down.
   */
  x_end_buffer: number
  /**
   * The end zone size (in mm). The distance from the end of the stroke where the device start to decelerate.
   */
  x_end_zone_size: number
  /**
   * The end zone speed (in mm/s). The speed the device will use in the end zone.
   */
  x_end_zone_speed: number
  /**
   * The minimum speed (in mm/s). The minimum speed the device will use.
   */
  x_min_speed: number
  /**
   * The maximum speed (in mm/s). The maximum speed the device will use.
   */
  x_max_speed: number
  /**
   * The theoretical minimum speed (in mm/s). The minimum speed the device can achieve in theory.
   */
  x_min_speed_theoretical: number
  /**
   * The theoretical maximum speed (in mm/s). The maximum speed the device can achieve in theory.
   */
  x_max_speed_theoretical: number
  /**
   * The turn time (in ms). The time the device will take to turn around at the end of the stroke.
   */
  turn_time: number
  /**
   * The regulator timeout (in ms).
   */
  regulator_timeout: number
  /**
   * The high temperature trigger (in °C). The temperature at which the device will trigger a high temperature warning.
   */
  temp_high_trigger: number
  /**
   * The temperature offset (in °C). The offset to apply to the temperature reading.
   */
  temp_offset: number
  /**
   * The minimum stroke (in mm). The minimum distance the slider can move.
   */
  x_stroke_min: number
  /**
   * The maximum stroke (in mm). The maximum distance the slider can move.
   */
  x_stroke_max: number
  /**
   * Hysteresis for the temperature triggers.
   */
  temp_hysteresis: number
  /**
   * Flag to indicate if overclocking is enabled.
   */
  overclock_enabled: boolean
  /**
   * Flag to indicate if the motor direction is inverted.
   */
  x_inverse_motor: boolean
  /**
   * Flag to indicate if the hall sensor direction is inverted.
   */
  x_inverse_hall: boolean
}

/**
 * Device response
 */
export type DeviceResponse = {
  /**
   * The device response result if the operation was successful and the operation returned data.
   */
  result?: {
    [key: string]: unknown
  }
  error?: DeviceError
}

/**
 * Device error information
 */
export type DeviceError = {
  /**
   * The device connection status.
   */
  connected: boolean
  /**
   * The error name.
   */
  name: string
  /**
   * The error message.
   */
  message: string
  /**
   * The error code.
   */
  code: number
  /**
   * Additional error data.
   */
  data?: {
    [key: string]: unknown
  }
}

/**
 * Error response
 */
export type ErrorResponse = {
  error?: {
    /**
     * The device connection status.
     */
    connected: boolean
    /**
     * The error name.
     */
    name: string
    /**
     * The error message.
     */
    message: string
    /**
     * The error code.
     */
    code: number
    /**
     * Additional error data.
     */
    data?: {
      [key: string]: unknown
    }
  }
}

/**
 * Network status
 */
export type InterfaceStatus = {
  /**
   * The WIFI interface status.
   */
  wifi: boolean
  /**
   * The BLE interface status.
   */
  ble: boolean
}

/**
 * Device capabilities
 */
export type DeviceCapabilities = {
  /**
   * The device is vulva oriented.
   */
  vulva_oriented?: boolean
  /**
   * The device has a battery.
   */
  battery?: boolean
  /**
   * The number of sliders.
   */
  slider?: number
  /**
   * The number of LRA motors.
   */
  lra?: number
  /**
   * The number of ERM motors.
   */
  erm?: number
  /**
   * The device has external memory.
   */
  external_memory?: boolean
  /**
   * The device has an RGB LED indicator.
   */
  rgb_led_indicator?: boolean
  /**
   * The device has an LED matrix.
   */
  led_matrix?: boolean
  /**
   * The number of LEDs in the x direction of the LED matrix.
   */
  led_matrix_leds_x?: number
  /**
   * The number of LEDs in the y direction of the LED matrix.
   */
  led_matrix_leds_y?: number
  /**
   * The device has an RGB ring.
   */
  rgb_ring?: boolean
  /**
   * The number of LEDs in the RGB ring.
   */
  rgb_ring_leds?: number
}

/**
 * Device ids
 */
export type DeviceSessionIds = {
  /**
   * The device boot session id. Set to a random value on each boot. Can be used to check for reboots.
   */
  boot_session_id?: number
  /**
   * The socket session id. Starts at 0 and increments each time the device connects to the server. Resets on boot. Can be used to check for reconnections within the same boot session.
   */
  socket_session_id?: number
  /**
   * The device mode session id. Starts at 0 and increments each time the device mode changes. Resets on boot. Can be used to check for mode changes within the same boot session.
   */
  mode_session_id?: number
}

/**
 * HSP add points request.
 */
export type HspAdd = {
  /**
   * The points to add to the HSP buffer.
   */
  points: Array<Point>
  /**
   * Flush the buffer before adding the points. This will remove all points from the buffer before adding the new points.
   */
  flush?: boolean
  /**
   * The tail point stream index. The index of the last point in the HSP buffer relative to the overall stream of points.
   */
  tail_point_stream_index: number
  /**
   * An optional tail point stream index threshold update. Applied after the points have been added.
   */
  tail_point_threshold?: number
}

/**
 * The playback rate.
 * A value of 1.0 will play the points at the original speed. A value of 0.5 will play the points at half speed. A value of 2.0 will play the points at double speed.
 *
 */
export type PlaybackRate = number

/**
 * When enabled, the device clock will pause when the device enters a starving state and resume when new points are added.
 * This prevents the clock from advancing while waiting for new points, eliminating the need to adjust timestamps to account for the starving period.
 *
 */
export type PauseOnStarving = boolean

/**
 * The estimated server time in milliseconds. If not provided, the actual current server time will be used. If you are trying to synchronize the device movement with some external source, this will negativly impact the synchronization accuracy.
 */
export type ServerTimeEstimate = number

/**
 * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
 * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
 * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
 * If you experience timeouts, you can try to increase the timeout value.
 *
 */
export type Timeout = number

/**
 * Device connection key.
 */
export type ConnectionKey2 = ConnectionKey

/**
 * A device connection key or a channel reference.
 */
export type DeviceReference = ConnectionKey | ChannelReference

/**
 * Optional event filter. If not specified, all events are pushed to the client.
 *
 */
export type EventFilter = Array<SseEventType>

export type IssueTokenData = {
  body?: never
  path?: never
  query?: {
    /**
     * The time-to-live (ttl) of the token in seconds. This defines how long the token remains valid. If not specified, a default value is used. Default is 1 hour (3600 seconds). Minimum is 60 seconds, maximum is 24 hours (86400 seconds).
     */
    ttl?: number
    /**
     * The device connection key for which the token is to be issued. Specifying this parameter restricts the use of the token to the specific device.
     */
    to?: string
    /**
     * The client IP address for which the token is to be issued. Specifying this parameter restricts the use of the token to requests originating from the specific IP address.
     */
    ip?: string
    /**
     * The client Origin header value prefix for which the token is to be issued. Specifying this parameter restricts the use of the token to requests with the specific Origin header value prefix.
     */
    origin?: string
    /**
     * The client Referer header value prefix for which the token is to be issued. Specifying this parameter restricts the use of the token to requests with the specific Referer header value prefix.
     */
    r?: string
    /**
     * The client User-Agent header value prefix for which the token is to be issued. Specifying this parameter restricts the use of the token to requests with the specific User-Agent header value prefix.
     */
    ua?: string
    /**
     * The client Accept-Language header value for which the token is to be issued. Specifying this parameter restricts the use of the token to requests with the specific Accept-Language header value.
     */
    al?: string
    /**
     * The client Accept-Encoding header value for which the token is to be issued. Specifying this parameter restricts the use of the token to requests with the specific Accept-Encoding header value.
     */
    ae?: string
    /**
     * The client Cache-Control header value for which the token is to be issued. Specifying this parameter restricts the use of the token to requests with the specific Cache-Control header value.
     */
    cc?: string
  }
  url: '/auth/token/issue'
}

export type IssueTokenErrors = {
  /**
   * Bad request.
   */
  400: unknown
  /**
   * Unauthorized
   */
  401: unknown
  /**
   * Forbidden
   */
  403: unknown
  /**
   * Request timeout.
   */
  408: unknown
  /**
   * Internal server error.
   */
  500: unknown
}

export type IssueTokenResponses = {
  /**
   * The issued token.
   */
  200: AuthTokenResponse
}

export type IssueTokenResponse = IssueTokenResponses[keyof IssueTokenResponses]

export type GetHampStateData = {
  body?: never
  headers: {
    /**
     * A device connection key or a channel reference.
     */
    'X-Connection-Key': ConnectionKey | ChannelReference
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/hamp/state'
}

export type GetHampStateResponses = {
  /**
   * HAMP state.
   */
  200: DeviceResponse & {
    result?: HampState
  }
}

export type GetHampStateResponse = GetHampStateResponses[keyof GetHampStateResponses]

export type StartHampData = {
  body?: never
  headers: {
    /**
     * A device connection key or a channel reference.
     */
    'X-Connection-Key': ConnectionKey | ChannelReference
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/hamp/start'
}

export type StartHampResponses = {
  /**
   * HAMP state.
   */
  200: DeviceResponse & {
    result?: HampState
  }
}

export type StartHampResponse = StartHampResponses[keyof StartHampResponses]

export type StopHampData = {
  body?: never
  headers: {
    /**
     * A device connection key or a channel reference.
     */
    'X-Connection-Key': ConnectionKey | ChannelReference
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/hamp/stop'
}

export type StopHampResponses = {
  /**
   * Device response.
   */
  200: DeviceResponse & {
    result?: HampState
  }
}

export type StopHampResponse = StopHampResponses[keyof StopHampResponses]

export type SetHampVelocityData = {
  /**
   * HAMP velocity
   */
  body: {
    velocity: HampVelocity
  }
  headers: {
    /**
     * A device connection key or a channel reference.
     */
    'X-Connection-Key': ConnectionKey | ChannelReference
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/hamp/velocity'
}

export type SetHampVelocityResponses = {
  /**
   * HAMP state.
   */
  200: DeviceResponse & {
    result?: HampState
  }
}

export type SetHampVelocityResponse = SetHampVelocityResponses[keyof SetHampVelocityResponses]

export type SetHampStrokeData = {
  /**
   * HAMP stroke settings
   */
  body: HampStrokeSettings
  headers: {
    /**
     * A device connection key or a channel reference.
     */
    'X-Connection-Key': ConnectionKey | ChannelReference
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/hamp/stroke'
}

export type SetHampStrokeResponses = {
  /**
   * HAMP state.
   */
  200: DeviceResponse & {
    result?: HampState
  }
}

export type SetHampStrokeResponse = SetHampStrokeResponses[keyof SetHampStrokeResponses]

export type GetSliderSettingsData = {
  body?: never
  headers: {
    /**
     * A device connection key or a channel reference.
     */
    'X-Connection-Key': ConnectionKey | ChannelReference
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/settings/slider'
}

export type GetSliderSettingsResponses = {
  /**
   * Device slider settings.
   */
  200: DeviceResponse & {
    result?: SliderSettings
  }
}

export type GetSliderSettingsResponse = GetSliderSettingsResponses[keyof GetSliderSettingsResponses]

export type GetDeviceInfoData = {
  body?: never
  headers: {
    /**
     * A device connection key or a channel reference.
     */
    'X-Connection-Key': ConnectionKey | ChannelReference
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/info'
}

export type GetDeviceInfoResponses = {
  /**
   * Device information.
   */
  200: DeviceResponse & {
    result?: DeviceInfo
  }
}

export type GetDeviceInfoResponse = GetDeviceInfoResponses[keyof GetDeviceInfoResponses]

export type GetModeData = {
  body?: never
  headers: {
    /**
     * A device connection key or a channel reference.
     */
    'X-Connection-Key': ConnectionKey | ChannelReference
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/mode'
}

export type GetModeResponses = {
  /**
   * Device mode.
   */
  200: DeviceResponse & {
    result?: DeviceMode
  }
}

export type GetModeResponse = GetModeResponses[keyof GetModeResponses]

export type SetModeData = {
  /**
   * Device mode
   */
  body: {
    mode: DeviceModeValue
  }
  headers: {
    /**
     * A device connection key or a channel reference.
     */
    'X-Connection-Key': ConnectionKey | ChannelReference
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/mode'
}

export type SetModeResponses = {
  /**
   * Device mode.
   */
  200: DeviceResponse & {
    result?: string
  }
}

export type SetModeResponse = SetModeResponses[keyof SetModeResponses]

export type SetMode2Data = {
  /**
   * Device mode
   */
  body: {
    mode: DeviceModeValue
  }
  headers: {
    /**
     * A device connection key or a channel reference.
     */
    'X-Connection-Key': ConnectionKey | ChannelReference
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/mode2'
}

export type SetMode2Responses = {
  /**
   * Device mode.
   */
  200: DeviceResponse & {
    result?: DeviceMode
  }
}

export type SetMode2Response = SetMode2Responses[keyof SetMode2Responses]

export type IsConnectedData = {
  body?: never
  headers: {
    /**
     * A device connection key or a channel reference.
     */
    'X-Connection-Key': ConnectionKey | ChannelReference
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/connected'
}

export type IsConnectedErrors = {
  /**
   * Bad request.
   */
  400: unknown
}

export type IsConnectedResponses = {
  /**
   * Machine connected status
   */
  200: DeviceResponse & {
    /**
     * Connected response
     */
    result?: {
      /**
       * Connected status
       */
      connected: boolean
    }
  }
}

export type IsConnectedResponse = IsConnectedResponses[keyof IsConnectedResponses]

export type GetEventsData = {
  body?: never
  headers: {
    /**
     * A device connection key or a channel reference.
     */
    'X-Connection-Key': ConnectionKey | ChannelReference
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
    /**
     * Optional event filter. If not specified, all events are pushed to the client.
     *
     */
    events?: Array<SseEventType>
  }
  url: '/sse'
}

export type GetEventsResponses = {
  /**
   * SSE stream of device events
   */
  200: string
}

export type GetEventsResponse = GetEventsResponses[keyof GetEventsResponses]

export type GetServerTimeData = {
  body?: never
  path?: never
  query?: never
  url: '/servertime'
}

export type GetServerTimeResponses = {
  /**
   * Server time.
   */
  200: {
    server_time: Timestamp
  }
}

export type GetServerTimeResponse = GetServerTimeResponses[keyof GetServerTimeResponses]

export type GetStatisticsData = {
  body?: never
  headers: {
    /**
     * Device connection key.
     */
    'X-Connection-Key': ConnectionKey
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/statistics'
}

export type GetStatisticsResponses = {
  /**
   * Device statistics.
   */
  200: DeviceResponse & {
    result?: DeviceStatistics
  }
}

export type GetStatisticsResponse = GetStatisticsResponses[keyof GetStatisticsResponses]

export type GetDeviceCapabilitiesData = {
  body?: never
  headers: {
    /**
     * Device connection key.
     */
    'X-Connection-Key': ConnectionKey
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/capabilities'
}

export type GetDeviceCapabilitiesResponses = {
  /**
   * Device capabilities.
   */
  200: DeviceResponse & {
    result?: DeviceCapabilities
  }
}

export type GetDeviceCapabilitiesResponse =
  GetDeviceCapabilitiesResponses[keyof GetDeviceCapabilitiesResponses]

export type GetDeviceSessionIdsData = {
  body?: never
  headers: {
    /**
     * Device connection key.
     */
    'X-Connection-Key': ConnectionKey
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/sids'
}

export type GetDeviceSessionIdsResponses = {
  /**
   * Device sessions IDs.
   */
  200: DeviceResponse & {
    result?: DeviceSessionIds
  }
}

export type GetDeviceSessionIdsResponse =
  GetDeviceSessionIdsResponses[keyof GetDeviceSessionIdsResponses]

export type SendXavaData = {
  /**
   * XAVA message
   */
  body: {
    /**
     * The absolute position to move the slider to.
     */
    xa: number
    /**
     * The absolute velocity to use when moving the slider to the target position.
     */
    va: number
    /**
     * Stop the device slider when the target position is reached.
     */
    stop_on_target?: boolean
    /**
     * Immediate response. Do not wait for device response.
     */
    immediate_rsp?: boolean
  }
  headers: {
    /**
     * Device connection key.
     */
    'X-Connection-Key': ConnectionKey
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/hdsp/xava'
}

export type SendXavaResponses = {
  /**
   * Command response.
   */
  200: DeviceResponse & {
    result?: unknown
  }
}

export type SendXavaResponse = SendXavaResponses[keyof SendXavaResponses]

export type SendXavpData = {
  /**
   * XAVP message
   */
  body: {
    /**
     * The relative position to move the slider to.
     */
    xa: number
    /**
     * The relative velocity to use when moving the slider to the target position.
     */
    vp: number
    /**
     * Stop the device slider when the target position is reached.
     */
    stop_on_target?: boolean
    /**
     * Immediate response. Do not wait for device response.
     */
    immediate_rsp?: boolean
  }
  headers: {
    /**
     * Device connection key.
     */
    'X-Connection-Key': ConnectionKey
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/hdsp/xavp'
}

export type SendXavpResponses = {
  /**
   * Command response. In case of a device error, the response will contain an ErrorResponse object.
   */
  200: DeviceResponse & {
    result?: unknown
  }
}

export type SendXavpResponse = SendXavpResponses[keyof SendXavpResponses]

export type SendXpvaData = {
  /**
   * XPVA message
   */
  body: {
    /**
     * The relative position to move the slider to.
     */
    xp: number
    /**
     * The absolute velocity to use when moving the slider to the target position.
     */
    va: number
    /**
     * Stop the device slider when the target position is reached.
     */
    stop_on_target?: boolean
    /**
     * Immediate response. Do not wait for device response.
     */
    immediate_rsp?: boolean
  }
  headers: {
    /**
     * Device connection key.
     */
    'X-Connection-Key': ConnectionKey
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/hdsp/xpva'
}

export type SendXpvaResponses = {
  /**
   * Command response. In case of a device error, the response will contain an ErrorResponse object.
   */
  200: DeviceResponse & {
    result?: unknown
  }
}

export type SendXpvaResponse = SendXpvaResponses[keyof SendXpvaResponses]

export type SendXpvpData = {
  /**
   * XPVP message
   */
  body: {
    /**
     * The relative position to move the slider to.
     */
    xp: number
    /**
     * The relative velocity to use when moving the slider to the target position.
     */
    va: number
    /**
     * Stop the device slider when the target position is reached.
     */
    stop_on_target?: boolean
    /**
     * Immediate response. Do not wait for device response.
     */
    immediate_rsp?: boolean
  }
  headers: {
    /**
     * Device connection key.
     */
    'X-Connection-Key': ConnectionKey
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/hdsp/xpvp'
}

export type SendXpvpResponses = {
  /**
   * Command response. In case of a device error, the response will contain an ErrorResponse object.
   */
  200: DeviceResponse & {
    result?: unknown
  }
}

export type SendXpvpResponse = SendXpvpResponses[keyof SendXpvpResponses]

export type SendXatData = {
  /**
   * XAT message
   */
  body: {
    /**
     * The absolute position to move the slider to.
     */
    xa: number
    /**
     * The time to use when moving the slider to the target position.
     */
    t: number
    /**
     * Stop the device slider when the target position is reached.
     */
    stop_on_target?: boolean
    /**
     * Immediate response. Do not wait for device response.
     */
    immediate_rsp?: boolean
  }
  headers: {
    /**
     * Device connection key.
     */
    'X-Connection-Key': ConnectionKey
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/hdsp/xat'
}

export type SendXatResponses = {
  /**
   * Device response. In case of a device error, the response will contain an ErrorResponse object.
   */
  200: DeviceResponse & {
    result?: unknown
  }
}

export type SendXatResponse = SendXatResponses[keyof SendXatResponses]

export type SendXptData = {
  /**
   * XAT message
   */
  body: {
    /**
     * The absolute position to move the slider to.
     */
    xp?: number
    /**
     * The time to use when moving the slider to the target position.
     */
    t?: number
    /**
     * Stop the device slider when the target position is reached.
     */
    stop_on_target?: boolean
    /**
     * Immediate response. Do not wait for device response.
     */
    immediate_rsp?: boolean
  }
  headers: {
    /**
     * Device connection key.
     */
    'X-Connection-Key': ConnectionKey
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/hdsp/xpt'
}

export type SendXptResponses = {
  /**
   * Command response. In case of a device error, the response will contain an ErrorResponse object.
   */
  200: DeviceResponse & {
    result?: unknown
  }
}

export type SendXptResponse = SendXptResponses[keyof SendXptResponses]

export type GetHsspStateData = {
  body?: never
  headers: {
    /**
     * A device connection key or a channel reference.
     */
    'X-Connection-Key': ConnectionKey | ChannelReference
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/hssp/state'
}

export type GetHsspStateResponses = {
  /**
   * HSSP state.
   */
  200: DeviceResponse & {
    result?: HspState
  }
}

export type GetHsspStateResponse = GetHsspStateResponses[keyof GetHsspStateResponses]

export type HsspSetupData = {
  body: HsspSetupUrl & {
    /**
     * When enabled the server will send HSP state change notifications over SSE.
     */
    notify?: boolean
  }
  headers: {
    /**
     * A device connection key or a channel reference.
     */
    'X-Connection-Key': ConnectionKey | ChannelReference
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/hssp/setup'
}

export type HsspSetupResponses = {
  /**
   * HSSP state.
   */
  200: DeviceResponse & {
    result?: HspState
  }
}

export type HsspSetupResponse = HsspSetupResponses[keyof HsspSetupResponses]

export type HsspPlayData = {
  /**
   * HSSP play
   */
  body: {
    /**
     * The start time in milliseconds.
     */
    start_time: number
    server_time: ServerTimeEstimate
    playback_rate?: PlaybackRate
    /**
     * The loop state.
     */
    loop?: boolean
  }
  headers: {
    /**
     * A device connection key or a channel reference.
     */
    'X-Connection-Key': ConnectionKey | ChannelReference
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/hssp/play'
}

export type HsspPlayResponses = {
  /**
   * HSSP state.
   */
  200: DeviceResponse & {
    result?: HspState
  }
}

export type HsspPlayResponse = HsspPlayResponses[keyof HsspPlayResponses]

export type HsspStopData = {
  body?: never
  headers: {
    /**
     * A device connection key or a channel reference.
     */
    'X-Connection-Key': ConnectionKey | ChannelReference
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/hssp/stop'
}

export type HsspStopResponses = {
  /**
   * HSSP state.
   */
  200: DeviceResponse & {
    result?: HspState
  }
}

export type HsspStopResponse = HsspStopResponses[keyof HsspStopResponses]

export type HsspPauseData = {
  body?: never
  headers: {
    /**
     * Device connection key.
     */
    'X-Connection-Key': ConnectionKey
  }
  path?: never
  query?: never
  url: '/hssp/pause'
}

export type HsspPauseResponses = {
  /**
   * HSSP state.
   */
  200: HspState
}

export type HsspPauseResponse = HsspPauseResponses[keyof HsspPauseResponses]

export type HsspResumeData = {
  /**
   * HSSP resume
   */
  body: {
    /**
     * If `true`, the playback will resume from the current 'live' position of the stream. If `false`, it will resume from the paused position.
     */
    pickUp?: boolean
  }
  headers: {
    /**
     * Device connection key.
     */
    'X-Connection-Key': ConnectionKey
  }
  path?: never
  query?: never
  url: '/hssp/resume'
}

export type HsspResumeResponses = {
  /**
   * HSSP state.
   */
  200: HspState
}

export type HsspResumeResponse = HsspResumeResponses[keyof HsspResumeResponses]

export type SetHsspTimeData = {
  /**
   * HSSP time
   */
  body: {
    /**
     * The time.
     */
    current_time: number
    server_time: ServerTimeEstimate
    /**
     * The filter to use when setting the time.
     */
    filter?: number
  }
  headers: {
    /**
     * A device connection key or a channel reference.
     */
    'X-Connection-Key': ConnectionKey | ChannelReference
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/hssp/synctime'
}

export type SetHsspTimeResponses = {
  /**
   * HSP state.
   */
  200: DeviceResponse & {
    result?: HspState
  }
}

export type SetHsspTimeResponse = SetHsspTimeResponses[keyof SetHsspTimeResponses]

export type HspSetupData = {
  /**
   * HSP setup
   */
  body?: {
    /**
     * The stream id.
     */
    stream_id?: number
  }
  headers: {
    /**
     * A device connection key or a channel reference.
     */
    'X-Connection-Key': ConnectionKey | ChannelReference
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/hsp/setup'
}

export type HspSetupResponses = {
  /**
   * HSP state.
   */
  200: DeviceResponse & {
    result?: HspState
  }
}

export type HspSetupResponse = HspSetupResponses[keyof HspSetupResponses]

export type HspFlushData = {
  body?: never
  headers: {
    /**
     * Device connection key.
     */
    'X-Connection-Key': ConnectionKey
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/hsp/flush'
}

export type HspFlushResponses = {
  /**
   * HSP state.
   */
  200: DeviceResponse & {
    result?: HspState
  }
}

export type HspFlushResponse = HspFlushResponses[keyof HspFlushResponses]

export type HspAddData = {
  /**
   * HSP point
   */
  body: HspAdd
  headers: {
    /**
     * Device connection key.
     */
    'X-Connection-Key': ConnectionKey
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/hsp/add'
}

export type HspAddResponses = {
  /**
   * HSSP state.
   */
  200: DeviceResponse & {
    result?: HspState
  }
}

export type HspAddResponse = HspAddResponses[keyof HspAddResponses]

export type HspPlayData = {
  /**
   * HSP play
   */
  body: {
    /**
     * The start time in milliseconds.
     */
    start_time: number
    server_time?: ServerTimeEstimate
    playback_rate?: PlaybackRate
    pause_on_starving?: PauseOnStarving
    /**
     * The loop state.
     */
    loop?: boolean
    add?: HspAdd
  }
  headers: {
    /**
     * Device connection key.
     */
    'X-Connection-Key': ConnectionKey
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/hsp/play'
}

export type HspPlayResponses = {
  /**
   * HSSP state.
   */
  200: DeviceResponse & {
    result?: HspState
  }
}

export type HspPlayResponse = HspPlayResponses[keyof HspPlayResponses]

export type HspStopData = {
  body?: never
  headers: {
    /**
     * Device connection key.
     */
    'X-Connection-Key': ConnectionKey
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/hsp/stop'
}

export type HspStopResponses = {
  /**
   * HSSP state.
   */
  200: DeviceResponse & {
    result?: HspState
  }
}

export type HspStopResponse = HspStopResponses[keyof HspStopResponses]

export type GetHspStateData = {
  body?: never
  headers: {
    /**
     * Device connection key.
     */
    'X-Connection-Key': ConnectionKey
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/hsp/state'
}

export type GetHspStateResponses = {
  /**
   * HSP state.
   */
  200: DeviceResponse & {
    result?: HspState
  }
}

export type GetHspStateResponse = GetHspStateResponses[keyof GetHspStateResponses]

export type SetHspThresholdData = {
  /**
   * HSP threshold
   */
  body: {
    /**
     * The HSP tail point stream index threshold.
     */
    tail_point_threshold: number
  }
  headers: {
    /**
     * Device connection key.
     */
    'X-Connection-Key': ConnectionKey
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/hsp/threshold'
}

export type SetHspThresholdResponses = {
  /**
   * HSP state.
   */
  200: DeviceResponse & {
    result?: HspState
  }
}

export type SetHspThresholdResponse = SetHspThresholdResponses[keyof SetHspThresholdResponses]

export type HspPauseData = {
  body?: never
  headers: {
    /**
     * Device connection key.
     */
    'X-Connection-Key': ConnectionKey
  }
  path?: never
  query?: never
  url: '/hsp/pause'
}

export type HspPauseResponses = {
  /**
   * HSP state.
   */
  200: HspState
}

export type HspPauseResponse = HspPauseResponses[keyof HspPauseResponses]

export type HspResumeData = {
  /**
   * HSP resume
   */
  body: {
    /**
     * If `true`, the playback will resume from the current 'live' position of the stream. If `false`, it will resume from the paused position.
     */
    pick_up?: boolean
  }
  headers: {
    /**
     * Device connection key.
     */
    'X-Connection-Key': ConnectionKey
  }
  path?: never
  query?: never
  url: '/hsp/resume'
}

export type HspResumeResponses = {
  /**
   * HSP state.
   */
  200: HspState
}

export type HspResumeResponse = HspResumeResponses[keyof HspResumeResponses]

export type SetHspPauseOnStarvingData = {
  /**
   * HSP pause-on-starving
   */
  body: {
    /**
     * The HSP pause-on-starving flag.
     */
    pause_on_starving: boolean
  }
  headers: {
    /**
     * Device connection key.
     */
    'X-Connection-Key': ConnectionKey
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/hsp/pause/onstarving'
}

export type SetHspPauseOnStarvingResponses = {
  /**
   * HSP state.
   */
  200: DeviceResponse & {
    result?: HspState
  }
}

export type SetHspPauseOnStarvingResponse =
  SetHspPauseOnStarvingResponses[keyof SetHspPauseOnStarvingResponses]

export type SetHspTimeData = {
  /**
   * HSP time
   */
  body: {
    /**
     * The time.
     */
    current_time: number
    server_time: ServerTimeEstimate
    /**
     * The filter to use when setting the time.
     */
    filter?: number
  }
  headers: {
    /**
     * Device connection key.
     */
    'X-Connection-Key': ConnectionKey
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/hsp/synctime'
}

export type SetHspTimeResponses = {
  /**
   * HSP state.
   */
  200: DeviceResponse & {
    result?: HspState
  }
}

export type SetHspTimeResponse = SetHspTimeResponses[keyof SetHspTimeResponses]

export type SetHspLoopData = {
  /**
   * HSP loop
   */
  body: {
    /**
     * The HSP loop flag.
     */
    loop: boolean
  }
  headers: {
    /**
     * Device connection key.
     */
    'X-Connection-Key': ConnectionKey
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/hsp/loop'
}

export type SetHspLoopResponses = {
  /**
   * HSP state.
   */
  200: DeviceResponse & {
    result?: HspState
  }
}

export type SetHspLoopResponse = SetHspLoopResponses[keyof SetHspLoopResponses]

export type SetHspPaybackRateData = {
  /**
   * HSP playback rate
   */
  body: {
    /**
     * The HSP playback_rate
     */
    playback_rate: number
  }
  headers: {
    /**
     * Device connection key.
     */
    'X-Connection-Key': ConnectionKey
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/hsp/playbackrate'
}

export type SetHspPaybackRateResponses = {
  /**
   * HSP state.
   */
  200: DeviceResponse & {
    result?: HspState
  }
}

export type SetHspPaybackRateResponse = SetHspPaybackRateResponses[keyof SetHspPaybackRateResponses]

export type GetDeviceTimeInfoData = {
  body?: never
  headers: {
    /**
     * Device connection key.
     */
    'X-Connection-Key': ConnectionKey
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/hstp/info'
}

export type GetDeviceTimeInfoErrors = {
  /**
   * Bad request.
   */
  400: unknown
}

export type GetDeviceTimeInfoResponses = {
  /**
   * DeviceTimeResponse
   */
  200: DeviceResponse & {
    result?: DeviceTimeInfo
  }
}

export type GetDeviceTimeInfoResponse = GetDeviceTimeInfoResponses[keyof GetDeviceTimeInfoResponses]

export type ClockSyncData = {
  body?: never
  headers: {
    /**
     * Device connection key.
     */
    'X-Connection-Key': ConnectionKey
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
    /**
     * If true, the clock sync response will be synchronous and the sync result will be returned in the response, in addition to published on the SSE stream. If false, the sync result will only be published on the SSE stream.
     */
    s?: boolean
  }
  url: '/hstp/clocksync'
}

export type ClockSyncErrors = {
  /**
   * Bad request.
   */
  400: unknown
}

export type ClockSyncResponses = {
  /**
   * DeviceTimeResponse
   */
  200: DeviceResponse & {
    result?: DeviceTimeInfo
  }
}

export type ClockSyncResponse = ClockSyncResponses[keyof ClockSyncResponses]

export type GetOffsetData = {
  body?: never
  headers: {
    /**
     * Device connection key.
     */
    'X-Connection-Key': ConnectionKey
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/hstp/offset'
}

export type GetOffsetErrors = {
  /**
   * Bad request.
   */
  400: unknown
}

export type GetOffsetResponses = {
  /**
   * DeviceTimeResponse
   */
  200: DeviceResponse & {
    result?: {
      offset: Timestamp
    }
  }
}

export type GetOffsetResponse = GetOffsetResponses[keyof GetOffsetResponses]

export type SetOffsetData = {
  /**
   * Offset value
   */
  body: {
    /**
     * The offset value in milliseconds.
     */
    offset: number
  }
  headers: {
    /**
     * Device connection key.
     */
    'X-Connection-Key': ConnectionKey
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/hstp/offset'
}

export type SetOffsetErrors = {
  /**
   * Bad request.
   */
  400: unknown
}

export type SetOffsetResponses = {
  /**
   * DeviceTimeResponse
   */
  200: DeviceResponse & {
    result?: string
  }
}

export type SetOffsetResponse = SetOffsetResponses[keyof SetOffsetResponses]

export type GetHvpStateData = {
  body?: never
  headers: {
    /**
     * Device connection key.
     */
    'X-Connection-Key': ConnectionKey
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/hvp/state'
}

export type GetHvpStateResponses = {
  /**
   * HVP state.
   */
  200: DeviceResponse & {
    result?: HvpState
  }
}

export type GetHvpStateResponse = GetHvpStateResponses[keyof GetHvpStateResponses]

export type SetHvpStateData = {
  /**
   * HVP set
   */
  body: {
    /**
     * The amplitude. A value between 0 and 1 (0-100%). For LRA, ERM and Sliders with vibration adapter (percent of valid output range)
     */
    amplitude: number
    /**
     * The frequency in Hz. 0-10000Hz. For LRA only
     */
    frequency: number
    /**
     * The position of the vibration (mm). Where on the slider should the vibration be. For slider with vibration adapter only.
     */
    position: number
  }
  headers: {
    /**
     * Device connection key.
     */
    'X-Connection-Key': ConnectionKey
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/hvp/state'
}

export type SetHvpStateResponses = {
  /**
   * HVP state.
   */
  200: DeviceResponse & {
    result?: HvpState
  }
}

export type SetHvpStateResponse = SetHvpStateResponses[keyof SetHvpStateResponses]

export type HvpStartData = {
  body?: never
  headers: {
    /**
     * Device connection key.
     */
    'X-Connection-Key': ConnectionKey
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/hvp/start'
}

export type HvpStartResponses = {
  /**
   * HVP state.
   */
  200: DeviceResponse & {
    result?: HvpState
  }
}

export type HvpStartResponse = HvpStartResponses[keyof HvpStartResponses]

export type HvpStopData = {
  body?: never
  headers: {
    /**
     * Device connection key.
     */
    'X-Connection-Key': ConnectionKey
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/hvp/stop'
}

export type HvpStopResponses = {
  /**
   * HVP state.
   */
  200: DeviceResponse & {
    result?: HvpState
  }
}

export type HvpStopResponse = HvpStopResponses[keyof HvpStopResponses]

export type GetSlideStateData = {
  body?: never
  headers: {
    /**
     * Device connection key.
     */
    'X-Connection-Key': ConnectionKey
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/slider/state'
}

export type GetSlideStateResponses = {
  /**
   * Slider state.
   */
  200: DeviceResponse & {
    result?: SliderState
  }
}

export type GetSlideStateResponse = GetSlideStateResponses[keyof GetSlideStateResponses]

export type GetStrokeData = {
  body?: never
  headers: {
    /**
     * A device connection key or a channel reference.
     */
    'X-Connection-Key': ConnectionKey | ChannelReference
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/slider/stroke'
}

export type GetStrokeErrors = {
  /**
   * Bad request.
   */
  400: unknown
}

export type GetStrokeResponses = {
  /**
   * Device response. In case of a device error, the response will contain an ErrorResponse object.
   */
  200: DeviceResponse & {
    result?: StrokeSettingsRsp
  }
}

export type GetStrokeResponse = GetStrokeResponses[keyof GetStrokeResponses]

export type SetStrokeData = {
  /**
   * Stroke settings
   */
  body: StrokeSettings
  headers: {
    /**
     * A device connection key or a channel reference.
     */
    'X-Connection-Key': ConnectionKey | ChannelReference
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/slider/stroke'
}

export type SetStrokeResponses = {
  /**
   * Device response. In case of a device error, the response will contain an ErrorResponse object.
   */
  200: DeviceResponse & {
    result?: StrokeSettingsRsp
  }
}

export type SetStrokeResponse = SetStrokeResponses[keyof SetStrokeResponses]

export type SetupStreamData = {
  /**
   * Stream setup
   */
  body: {
    /**
     * The stream reference of the stream to play.
     */
    stream_ref: string
    /**
     * Enable HSP notifications for the stream playback. STREAM supresses HSP notifications by default since for most use cases they are not needed, since pushing data to the device is handled server side.
     */
    notify?: boolean
  }
  headers: {
    /**
     * A device connection key or a channel reference.
     */
    'X-Connection-Key': ConnectionKey | ChannelReference
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/stream/setup'
}

export type SetupStreamResponses = {
  /**
   * Stream state.
   */
  200: DeviceResponse & {
    result?: HspState
  }
}

export type SetupStreamResponse = SetupStreamResponses[keyof SetupStreamResponses]

export type StreamPlayData = {
  /**
   * Stream play
   */
  body: {
    /**
     * The start time in milliseconds.
     */
    start_time: number
    server_time: ServerTimeEstimate
    playback_rate?: PlaybackRate
    /**
     * The loop state.
     */
    loop?: boolean
    pause_on_starving?: PauseOnStarving
  }
  headers: {
    /**
     * A device connection key or a channel reference.
     */
    'X-Connection-Key': ConnectionKey | ChannelReference
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/stream/play'
}

export type StreamPlayResponses = {
  /**
   * Stream state.
   */
  200: DeviceResponse & {
    result?: HspState
  }
}

export type StreamPlayResponse = StreamPlayResponses[keyof StreamPlayResponses]

export type StreamStopData = {
  body?: never
  headers: {
    /**
     * A device connection key or a channel reference.
     */
    'X-Connection-Key': ConnectionKey | ChannelReference
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/stream/stop'
}

export type StreamStopResponses = {
  /**
   * Stream state.
   */
  200: DeviceResponse & {
    result?: HspState
  }
}

export type StreamStopResponse = StreamStopResponses[keyof StreamStopResponses]

export type GetStreamStateData = {
  body?: never
  headers: {
    /**
     * A device connection key or a channel reference.
     */
    'X-Connection-Key': ConnectionKey | ChannelReference
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/stream/state'
}

export type GetStreamStateResponses = {
  /**
   * Stream state.
   */
  200: DeviceResponse & {
    result?: HspState
  }
}

export type GetStreamStateResponse = GetStreamStateResponses[keyof GetStreamStateResponses]

export type SetStreamTimeData = {
  /**
   * STREAM time
   */
  body: {
    /**
     * The time.
     */
    current_time: number
    server_time: ServerTimeEstimate
    /**
     * The filter to use when setting the time.
     */
    filter?: number
  }
  headers: {
    /**
     * A device connection key or a channel reference.
     */
    'X-Connection-Key': ConnectionKey | ChannelReference
  }
  path?: never
  query?: {
    /**
     * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
     * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
     * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
     * If you experience timeouts, you can try to increase the timeout value.
     *
     */
    timeout?: number
  }
  url: '/stream/synctime'
}

export type SetStreamTimeResponses = {
  /**
   * HSP state.
   */
  200: DeviceResponse & {
    result?: HspState
  }
}

export type SetStreamTimeResponse = SetStreamTimeResponses[keyof SetStreamTimeResponses]
