// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod'

/**
 * Generic error response
 */
export const zGenericError = z.object({
  name: z.string(),
  message: z.optional(z.string()),
  code: z.int(),
  data: z.optional(z.record(z.string(), z.unknown())),
})

/**
 * Possible device modes.
 * <br><br>
 * - 0: hamp
 * - 1: hssp
 * - 2: hdsp
 * - 3: maintenance
 * - 4: hsp
 * - 5: ota
 * - 6: button
 * - 7: idle
 * - 8: vibrate
 * - 9: hrpp
 *
 */
export const zDeviceModeValue = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
  z.literal(5),
  z.literal(6),
  z.literal(7),
  z.literal(8),
])

/**
 * Device mode response
 */
export const zDeviceMode = z.object({
  mode: zDeviceModeValue,
  mode_session_id: z.optional(z.number()),
})

export const zTimestamp = z.int().gte(0)

export const zDateTime = z.iso.datetime()

/**
 * Client token
 */
export const zClientToken = z.object({
  token_ref: z.string(),
  created_at: zDateTime,
  expires_at: zDateTime,
  token: z.string(),
  renew: z.string(),
})

/**
 * Auth token response
 */
export const zAuthTokenResponse = z.object({
  result: z.optional(zClientToken),
  error: z.optional(zGenericError),
})

export const zConnectionKey = z
  .string()
  .min(5)
  .max(64)
  .regex(/^[a-zA-Z0-9]{5,64}$/)

/**
 * Device environment.
 * <br><br>
 * - 0: production
 * - 1: staging
 * - 2: development
 *
 */
export const zDeviceEnvironment = z.union([z.literal(0), z.literal(1), z.literal(2)])

/**
 * Connection mode.
 * <br><br>
 * - 0: none
 * - 1: WIFI
 * - 2: BLE
 * - 3: WIFI_BLE
 * - 4: OFFLINE
 * - 5: LEGACY_BLE
 *
 */
export const zConnectionMode = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
  z.literal(5),
])

export const zChannelReference = z
  .string()
  .min(5)
  .max(64)
  .regex(/^(chref:?:)?[a-zA-Z0-9]{5,64}$/)

/**
 * The event type
 */
export const zSseEventType = z.enum([
  'battery_changed',
  'ble_status_changed',
  'button_event',
  'device_clock_synchronized',
  'device_connected',
  'device_disconnected',
  'device_error',
  'device_status',
  'hamp_state_changed',
  'hrpp_state_changed',
  'hdsp_state_changed',
  'hsp_looping',
  'hsp_starving',
  'hsp_state_changed',
  'hsp_threshold_reached',
  'stream_end_reached',
  'hvp_state_changed',
  'low_memory_error',
  'low_memory_warning',
  'mode_changed',
  'ota_progress',
  'slider_blocked',
  'slider_unblocked',
  'stroke_changed',
  'temp_high',
  'temp_ok',
  'wifi_scan_complete',
  'wifi_status',
  'wifi_status_changed',
])

/**
 * The current HDSP state.<br>
 * Possible values:
 * - 0: stopped
 * - 1: moving
 * - 2: point reached
 *
 */
export const zHdspStateValue = z.union([z.literal(0), z.literal(1), z.literal(2)])

/**
 * HDSP state
 */
export const zHdspState = z.object({
  state: zHdspStateValue,
})

/**
 * HVP state
 */
export const zHvpState = z.object({
  enabled: z.boolean(),
  amplitude: z.number(),
  frequency: z.number(),
  position: z.number(),
})

/**
 * Error data
 */
export const zErrorData = z.object({
  code: z.int(),
  message: z.string(),
})

/**
 * The button pressed.<br>
 * Possible values:
 * - 0: power
 * - 1: up
 * - 2: left
 * - 3: right
 * - 4: down
 * - 5: Wifi
 *
 */
export const zButtonValue = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
  z.literal(5),
])

/**
 * The button press type.<br>
 * Possible values:
 * - 0: pressed
 * - 1: released
 * - 2: short press
 * - 3: long press start
 * - 4: long press step
 * - 5: long press end
 *
 */
export const zButtonEventType = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
  z.literal(5),
])

/**
 * Button event data
 */
export const zButtonEvent = z.object({
  button: zButtonValue,
  event: zButtonEventType,
})

/**
 * OTA status
 */
export const zOtaProgress = z.object({
  done: z.boolean(),
  progress: z.number(),
  failed: z.boolean(),
})

/**
 * Stroke status
 */
export const zStrokeStatus = z.object({
  min: z.number(),
  max: z.number(),
  min_absolute: z.number(),
  max_absolute: z.number(),
})

/**
 * Battery status
 */
export const zBatteryStatus = z.object({
  level: z.number(),
  charger_connected: z.boolean(),
  charging_complete: z.boolean(),
  usb_voltage: z.number(),
  battery_voltage: z.number(),
  usb_adc_value: z.int(),
  battery_adc_value: z.int(),
})

/**
 * Low memory warning event data
 */
export const zLowMemoryWarning = z.object({
  available_heap: z.int(),
  larges_free_block: z.int(),
})

/**
 * Low memory error event data
 */
export const zLowMemoryError = z.object({
  available_heap: z.int(),
  larges_free_block: z.int(),
  discarded_msg_size: z.int(),
})

/**
 * WIFI scan complete event data
 */
export const zWifiScanComplete = z.object({
  nr_of_networks: z.int(),
})

/**
 * The WIFI state.<br>
 * Possible values:
 * - 0: Disconnected
 * - 1: Connected
 * - 2: Connecting
 * - 3: Reconneting
 * - 4: Failed to connect
 * - 5: Disconnecting
 *
 */
export const zWifiStateValue = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
  z.literal(5),
])

/**
 * WIFI status
 */
export const zWifiStatus = z.object({
  socket_connected: z.boolean(),
  state: zWifiStateValue,
})

/**
 * The BLE status.<br>
 * Possible values:
 * - 0: Not initialized
 * - 1: Initializing
 * - 2: Advertising
 * - 3: Connected
 *
 */
export const zBleStatusValue = z.union([z.literal(0), z.literal(1), z.literal(2), z.literal(3)])

/**
 * BLE status
 */
export const zBleStatus = z.object({
  status: zBleStatusValue,
})

/**
 * Device disconnected event data
 */
export const zDeviceDisconnected = z.object({
  reason: z.string(),
  session_id: z.string(),
  timestamp: z.string(),
})

/**
 * Device statistics
 */
export const zDeviceStatistics = z.object({
  timestamp: zDateTime,
  transit_size: z.optional(z.int()),
  max_transit_size: z.optional(z.int()),
  buffer_size: z.optional(z.int()),
  max_buffer_size: z.optional(z.int()),
  total_bytes: z.optional(z.int()),
  total_messages: z.optional(z.int()),
  dropped_bytes: z.optional(z.int()),
  dropped_messages: z.optional(z.int()),
  acked_bytes: z.optional(z.int()),
  acked_messages: z.optional(z.int()),
})

/**
 * The velocity of the HAMP device. [0-1] 1=100% of max velocity.
 */
export const zHampVelocity = z.number().gte(0).lte(1)

/**
 * HAMP play state.
 * <br><br>
 * - 0: stopped
 * - 1: playing
 *
 */
export const zHampPlayState = z.union([z.literal(0), z.literal(1)])

/**
 * HAMP state
 */
export const zHampState = z.object({
  play_state: zHampPlayState,
  velocity: z.number(),
  direction: z.boolean(),
})

export const zHsspSetupUrl = z.object({
  url: z.string(),
})

export const zHsspSetupCsv = z.object({
  csv: z.string(),
})

/**
 * HSSP play state.<br>
 * - 0: Not initialized
 * - 1: playing
 * - 2: stopped
 * - 3: paused
 * - 4: starving
 *
 */
export const zHspPlayState = z.union([
  z.literal(0),
  z.literal(1),
  z.literal(2),
  z.literal(3),
  z.literal(4),
])

/**
 * The position of the point. For devices with a slider this is the relative position [0,100] [0=bottom, 100=top] of the slider length.
 */
export const zPointPosition = z.int().gte(0).lte(50)

/**
 * The timestamp of a point in milliseconds relative to the start time (t=0).
 */
export const zPointTime = z.int().gte(0)

/**
 * Funscript action
 */
export const zAction = z.object({
  at: zPointTime,
  pos: zPointPosition,
})

export const zHsspSetupFunscript = z.object({
  actions: z.array(zAction),
})

/**
 * HSP point
 */
export const zPoint = z.object({
  t: zPointTime,
  x: zPointPosition,
})

/**
 * Slider state
 */
export const zSliderState = z.object({
  position: z.number(),
  position_absolute: z.number(),
  motor_temp: z.number(),
  speed_absolute: z.number(),
  dir: z.boolean(),
  motor_position: z.int(),
  motor_temp_adc_value: z.optional(z.int()),
})

export const zStrokeSettings = z.object({
  min: z.number(),
  max: z.number(),
})

export const zHampStrokeSettings = z.object({
  min: z.number(),
  max: z.number(),
})

export const zStrokeSettingsRsp = z.object({
  min: z.number(),
  max: z.number(),
  min_absolute: z.number(),
  max_absolute: z.number(),
})

/**
 * Firmware feature flags
 */
export const zFirmwareFeatureFlags = z.enum(['production', 'staging', 'development', 'other'])

export const zDeviceTimeInfo = z.object({
  time: z.int(),
  clock_offset: z.int(),
  rtd: z.int(),
})

/**
 * Firmware status.
 * <br><br>
 * - 0: up-to-date
 * - 1: update-available
 * - 2: update-required
 *
 */
export const zFirmwareStatus = z.union([z.literal(0), z.literal(1), z.literal(2)])

export const zDeviceInfo = z.object({
  fw_status: zFirmwareStatus,
  fw_version: z.string(),
  fw_feature_flags: z.optional(zFirmwareFeatureFlags),
  hw_model_no: z.optional(z.int()),
  hw_model_name: z.optional(z.string()),
  hw_model_variant: z.optional(z.int()),
  session_id: z.string(),
})

/**
 * Device status
 */
export const zDeviceStatus = z.object({
  connected: z.boolean(),
  info: z.optional(zDeviceInfo),
})

/**
 * Device settings
 */
export const zSliderSettings = z.object({
  x_limit_start: z.number(),
  x_limit_stop: z.number(),
  x_end_buffer: z.number(),
  x_end_zone_size: z.number(),
  x_end_zone_speed: z.number(),
  x_min_speed: z.number(),
  x_max_speed: z.number(),
  x_min_speed_theoretical: z.number(),
  x_max_speed_theoretical: z.number(),
  turn_time: z.number(),
  regulator_timeout: z.number(),
  temp_high_trigger: z.number(),
  temp_offset: z.number(),
  x_stroke_min: z.number(),
  x_stroke_max: z.number(),
  temp_hysteresis: z.number(),
  overclock_enabled: z.boolean(),
  x_inverse_motor: z.boolean(),
  x_inverse_hall: z.boolean(),
})

/**
 * Device error information
 */
export const zDeviceError = z.object({
  connected: z.boolean(),
  name: z.string(),
  message: z.string(),
  code: z.int(),
  data: z.optional(z.record(z.string(), z.unknown())),
})

/**
 * Device response
 */
export const zDeviceResponse = z.object({
  result: z.optional(z.record(z.string(), z.unknown())),
  error: z.optional(zDeviceError),
})

/**
 * Error response
 */
export const zErrorResponse = z.object({
  error: z.optional(
    z.object({
      connected: z.boolean(),
      name: z.string(),
      message: z.string(),
      code: z.int(),
      data: z.optional(z.record(z.string(), z.unknown())),
    }),
  ),
})

/**
 * Network status
 */
export const zInterfaceStatus = z.object({
  wifi: z.boolean(),
  ble: z.boolean(),
})

/**
 * Device capabilities
 */
export const zDeviceCapabilities = z.object({
  vulva_oriented: z.optional(z.boolean()),
  battery: z.optional(z.boolean()),
  slider: z.optional(z.int()),
  lra: z.optional(z.int()),
  erm: z.optional(z.int()),
  external_memory: z.optional(z.boolean()),
  rgb_led_indicator: z.optional(z.boolean()),
  led_matrix: z.optional(z.boolean()),
  led_matrix_leds_x: z.optional(z.int()),
  led_matrix_leds_y: z.optional(z.int()),
  rgb_ring: z.optional(z.boolean()),
  rgb_ring_leds: z.optional(z.int()),
})

/**
 * Device ids
 */
export const zDeviceSessionIds = z.object({
  boot_session_id: z.optional(z.int()),
  socket_session_id: z.optional(z.int()),
  mode_session_id: z.optional(z.int()),
})

/**
 * HSP add points request.
 */
export const zHspAdd = z.object({
  points: z.array(zPoint).max(100),
  flush: z.optional(z.boolean()).default(false),
  tail_point_stream_index: z.int().gte(1),
  tail_point_threshold: z.optional(z.int().gte(1)),
})

/**
 * The playback rate.
 * A value of 1.0 will play the points at the original speed. A value of 0.5 will play the points at half speed. A value of 2.0 will play the points at double speed.
 *
 */
export const zPlaybackRate = z.number().default(1)

/**
 * When enabled, the device clock will pause when the device enters a starving state and resume when new points are added.
 * This prevents the clock from advancing while waiting for new points, eliminating the need to adjust timestamps to account for the starving period.
 *
 */
export const zPauseOnStarving = z.boolean().default(false)

/**
 * HSP state
 */
export const zHspState = z.object({
  play_state: zHspPlayState,
  points: z.int(),
  pause_on_starving: zPauseOnStarving,
  max_points: z.number(),
  current_point: z.int(),
  current_time: z.int(),
  loop: z.boolean(),
  playback_rate: z.number(),
  first_point_time: z.int(),
  last_point_time: z.int(),
  stream_id: z.int(),
  tail_point_stream_index: z.int(),
  tail_point_stream_index_threshold: z.int(),
})

/**
 * SSE device data
 */
export const zSseEventData = z.object({
  connection_key: zConnectionKey,
  data: z.optional(
    z.union([
      zDeviceInfo,
      zDeviceDisconnected,
      zButtonEvent,
      zBleStatus,
      zWifiStatus,
      zWifiScanComplete,
      zLowMemoryWarning,
      zLowMemoryError,
      zBatteryStatus,
      zStrokeStatus,
      zOtaProgress,
      zHdspState,
      zHampState,
      zHspState,
      zHvpState,
      zErrorData,
      zDeviceStatus,
      zDeviceMode,
      zDeviceTimeInfo,
    ]),
  ),
})

/**
 * SSE event
 */
export const zSseEvent = z.object({
  id: z.string(),
  type: zSseEventType,
  data: zSseEventData,
})

/**
 * The estimated server time in milliseconds. If not provided, the actual current server time will be used. If you are trying to synchronize the device movement with some external source, this will negativly impact the synchronization accuracy.
 */
export const zServerTimeEstimate = z.int()

/**
 * The timeout in milliseconds for the operation. If the device does not respond within the set timeout, a device timeout error response is returned.
 * If not specified, a default value of 5000 milliseconds is used. The default value should be more then long enough under normal circumstances.
 * If a device has a very high RTD (round trip delay) or is under heavy load, the timeout value may need to be increased.
 * If you experience timeouts, you can try to increase the timeout value.
 *
 */
export const zTimeout = z.int().gte(5000).lte(60000).default(5000)

/**
 * Device connection key.
 */
export const zConnectionKey2 = zConnectionKey

/**
 * A device connection key or a channel reference.
 */
export const zDeviceReference = z.union([zConnectionKey, zChannelReference])

/**
 * Optional event filter. If not specified, all events are pushed to the client.
 *
 */
export const zEventFilter = z.array(zSseEventType)

export const zIssueTokenData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      ttl: z.optional(z.int().gte(60).lte(86400)).default(3600),
      to: z.optional(z.string()),
      ip: z.optional(z.string()),
      origin: z.optional(z.string()),
      r: z.optional(z.string()),
      ua: z.optional(z.string()),
      al: z.optional(z.string()),
      ae: z.optional(z.string()),
      cc: z.optional(z.string()),
    }),
  ),
})

/**
 * The issued token.
 */
export const zIssueTokenResponse = zAuthTokenResponse

export const zGetHampStateData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': z.union([zConnectionKey, zChannelReference]),
  }),
})

/**
 * HAMP state.
 */
export const zGetHampStateResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zHampState),
  }),
)

export const zStartHampData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': z.union([zConnectionKey, zChannelReference]),
  }),
})

/**
 * HAMP state.
 */
export const zStartHampResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zHampState),
  }),
)

export const zStopHampData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': z.union([zConnectionKey, zChannelReference]),
  }),
})

/**
 * Device response.
 */
export const zStopHampResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zHampState),
  }),
)

export const zSetHampVelocityData = z.object({
  body: z.object({
    velocity: zHampVelocity,
  }),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': z.union([zConnectionKey, zChannelReference]),
  }),
})

/**
 * HAMP state.
 */
export const zSetHampVelocityResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zHampState),
  }),
)

export const zSetHampStrokeData = z.object({
  body: zHampStrokeSettings,
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': z.union([zConnectionKey, zChannelReference]),
  }),
})

/**
 * HAMP state.
 */
export const zSetHampStrokeResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zHampState),
  }),
)

export const zGetSliderSettingsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': z.union([zConnectionKey, zChannelReference]),
  }),
})

/**
 * Device slider settings.
 */
export const zGetSliderSettingsResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zSliderSettings),
  }),
)

export const zGetDeviceInfoData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': z.union([zConnectionKey, zChannelReference]),
  }),
})

/**
 * Device information.
 */
export const zGetDeviceInfoResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zDeviceInfo),
  }),
)

export const zGetModeData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': z.union([zConnectionKey, zChannelReference]),
  }),
})

/**
 * Device mode.
 */
export const zGetModeResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zDeviceMode),
  }),
)

export const zSetModeData = z.object({
  body: z.object({
    mode: zDeviceModeValue,
  }),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': z.union([zConnectionKey, zChannelReference]),
  }),
})

/**
 * Device mode.
 */
export const zSetModeResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(z.string()),
  }),
)

export const zSetMode2Data = z.object({
  body: z.object({
    mode: zDeviceModeValue,
  }),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': z.union([zConnectionKey, zChannelReference]),
  }),
})

/**
 * Device mode.
 */
export const zSetMode2Response = zDeviceResponse.and(
  z.object({
    result: z.optional(zDeviceMode),
  }),
)

export const zIsConnectedData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': z.union([zConnectionKey, zChannelReference]),
  }),
})

/**
 * Machine connected status
 */
export const zIsConnectedResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(
      z.object({
        connected: z.boolean(),
      }),
    ),
  }),
)

export const zGetEventsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
      events: z.optional(z.array(zSseEventType)),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': z.union([zConnectionKey, zChannelReference]),
  }),
})

/**
 * SSE stream of device events
 */
export const zGetEventsResponse = z.string()

export const zGetServerTimeData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Server time.
 */
export const zGetServerTimeResponse = z.object({
  server_time: zTimestamp,
})

export const zGetStatisticsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': zConnectionKey,
  }),
})

/**
 * Device statistics.
 */
export const zGetStatisticsResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zDeviceStatistics),
  }),
)

export const zGetDeviceCapabilitiesData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': zConnectionKey,
  }),
})

/**
 * Device capabilities.
 */
export const zGetDeviceCapabilitiesResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zDeviceCapabilities),
  }),
)

export const zGetDeviceSessionIdsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': zConnectionKey,
  }),
})

/**
 * Device sessions IDs.
 */
export const zGetDeviceSessionIdsResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zDeviceSessionIds),
  }),
)

export const zSendXavaData = z.object({
  body: z.object({
    xa: z.number(),
    va: z.number(),
    stop_on_target: z.optional(z.boolean()).default(false),
    immediate_rsp: z.optional(z.boolean()).default(false),
  }),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': zConnectionKey,
  }),
})

/**
 * Command response.
 */
export const zSendXavaResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(z.unknown()),
  }),
)

export const zSendXavpData = z.object({
  body: z.object({
    xa: z.number(),
    vp: z.number().gte(0).lte(100),
    stop_on_target: z.optional(z.boolean()).default(false),
    immediate_rsp: z.optional(z.boolean()).default(false),
  }),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': zConnectionKey,
  }),
})

/**
 * Command response. In case of a device error, the response will contain an ErrorResponse object.
 */
export const zSendXavpResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(z.unknown()),
  }),
)

export const zSendXpvaData = z.object({
  body: z.object({
    xp: z.number().gte(0).lte(100),
    va: z.number(),
    stop_on_target: z.optional(z.boolean()).default(false),
    immediate_rsp: z.optional(z.boolean()).default(false),
  }),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': zConnectionKey,
  }),
})

/**
 * Command response. In case of a device error, the response will contain an ErrorResponse object.
 */
export const zSendXpvaResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(z.unknown()),
  }),
)

export const zSendXpvpData = z.object({
  body: z.object({
    xp: z.number().gte(0).lte(100),
    va: z.number().gte(0).lte(100),
    stop_on_target: z.optional(z.boolean()).default(false),
    immediate_rsp: z.optional(z.boolean()).default(false),
  }),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': zConnectionKey,
  }),
})

/**
 * Command response. In case of a device error, the response will contain an ErrorResponse object.
 */
export const zSendXpvpResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(z.unknown()),
  }),
)

export const zSendXatData = z.object({
  body: z.object({
    xa: z.number(),
    t: z.number(),
    stop_on_target: z.optional(z.boolean()).default(false),
    immediate_rsp: z.optional(z.boolean()).default(false),
  }),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': zConnectionKey,
  }),
})

/**
 * Device response. In case of a device error, the response will contain an ErrorResponse object.
 */
export const zSendXatResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(z.unknown()),
  }),
)

export const zSendXptData = z.object({
  body: z.object({
    xp: z.optional(z.number().gte(0).lte(100)),
    t: z.optional(z.number()),
    stop_on_target: z.optional(z.boolean()).default(false),
    immediate_rsp: z.optional(z.boolean()).default(false),
  }),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': zConnectionKey,
  }),
})

/**
 * Command response. In case of a device error, the response will contain an ErrorResponse object.
 */
export const zSendXptResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(z.unknown()),
  }),
)

export const zGetHsspStateData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': z.union([zConnectionKey, zChannelReference]),
  }),
})

/**
 * HSSP state.
 */
export const zGetHsspStateResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zHspState),
  }),
)

export const zHsspSetupData = z.object({
  body: zHsspSetupUrl.and(
    z.object({
      notify: z.optional(z.boolean()).default(false),
    }),
  ),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': z.union([zConnectionKey, zChannelReference]),
  }),
})

/**
 * HSSP state.
 */
export const zHsspSetupResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zHspState),
  }),
)

export const zHsspPlayData = z.object({
  body: z.object({
    start_time: z.int(),
    server_time: zServerTimeEstimate,
    playback_rate: z.optional(zPlaybackRate),
    loop: z.optional(z.boolean()).default(false),
  }),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': z.union([zConnectionKey, zChannelReference]),
  }),
})

/**
 * HSSP state.
 */
export const zHsspPlayResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zHspState),
  }),
)

export const zHsspStopData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': z.union([zConnectionKey, zChannelReference]),
  }),
})

/**
 * HSSP state.
 */
export const zHsspStopResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zHspState),
  }),
)

export const zHsspPauseData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
  headers: z.object({
    'X-Connection-Key': zConnectionKey,
  }),
})

/**
 * HSSP state.
 */
export const zHsspPauseResponse = zHspState

export const zHsspResumeData = z.object({
  body: z.object({
    pickUp: z.optional(z.boolean()).default(false),
  }),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
  headers: z.object({
    'X-Connection-Key': zConnectionKey,
  }),
})

/**
 * HSSP state.
 */
export const zHsspResumeResponse = zHspState

export const zSetHsspTimeData = z.object({
  body: z.object({
    current_time: z.int(),
    server_time: zServerTimeEstimate,
    filter: z.optional(z.number()),
  }),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': z.union([zConnectionKey, zChannelReference]),
  }),
})

/**
 * HSP state.
 */
export const zSetHsspTimeResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zHspState),
  }),
)

export const zHspSetupData = z.object({
  body: z.optional(
    z.object({
      stream_id: z.optional(z.int().gte(1).lte(4294967295)),
    }),
  ),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': z.union([zConnectionKey, zChannelReference]),
  }),
})

/**
 * HSP state.
 */
export const zHspSetupResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zHspState),
  }),
)

export const zHspFlushData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': zConnectionKey,
  }),
})

/**
 * HSP state.
 */
export const zHspFlushResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zHspState),
  }),
)

export const zHspAddData = z.object({
  body: zHspAdd,
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': zConnectionKey,
  }),
})

/**
 * HSSP state.
 */
export const zHspAddResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zHspState),
  }),
)

export const zHspPlayData = z.object({
  body: z.object({
    start_time: z.int(),
    server_time: z.optional(zServerTimeEstimate),
    playback_rate: z.optional(zPlaybackRate),
    pause_on_starving: z.optional(zPauseOnStarving),
    loop: z.optional(z.boolean()).default(false),
    add: z.optional(zHspAdd),
  }),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': zConnectionKey,
  }),
})

/**
 * HSSP state.
 */
export const zHspPlayResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zHspState),
  }),
)

export const zHspStopData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': zConnectionKey,
  }),
})

/**
 * HSSP state.
 */
export const zHspStopResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zHspState),
  }),
)

export const zGetHspStateData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': zConnectionKey,
  }),
})

/**
 * HSP state.
 */
export const zGetHspStateResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zHspState),
  }),
)

export const zSetHspThresholdData = z.object({
  body: z.object({
    tail_point_threshold: z.int().gte(1),
  }),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': zConnectionKey,
  }),
})

/**
 * HSP state.
 */
export const zSetHspThresholdResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zHspState),
  }),
)

export const zHspPauseData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
  headers: z.object({
    'X-Connection-Key': zConnectionKey,
  }),
})

/**
 * HSP state.
 */
export const zHspPauseResponse = zHspState

export const zHspResumeData = z.object({
  body: z.object({
    pick_up: z.optional(z.boolean()).default(false),
  }),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
  headers: z.object({
    'X-Connection-Key': zConnectionKey,
  }),
})

/**
 * HSP state.
 */
export const zHspResumeResponse = zHspState

export const zSetHspPauseOnStarvingData = z.object({
  body: z.object({
    pause_on_starving: z.boolean().default(false),
  }),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': zConnectionKey,
  }),
})

/**
 * HSP state.
 */
export const zSetHspPauseOnStarvingResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zHspState),
  }),
)

export const zSetHspTimeData = z.object({
  body: z.object({
    current_time: z.int(),
    server_time: zServerTimeEstimate,
    filter: z.optional(z.number()),
  }),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': zConnectionKey,
  }),
})

/**
 * HSP state.
 */
export const zSetHspTimeResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zHspState),
  }),
)

export const zSetHspLoopData = z.object({
  body: z.object({
    loop: z.boolean().default(false),
  }),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': zConnectionKey,
  }),
})

/**
 * HSP state.
 */
export const zSetHspLoopResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zHspState),
  }),
)

export const zSetHspPaybackRateData = z.object({
  body: z.object({
    playback_rate: z.number().default(1),
  }),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': zConnectionKey,
  }),
})

/**
 * HSP state.
 */
export const zSetHspPaybackRateResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zHspState),
  }),
)

export const zGetDeviceTimeInfoData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': zConnectionKey,
  }),
})

/**
 * DeviceTimeResponse
 */
export const zGetDeviceTimeInfoResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zDeviceTimeInfo),
  }),
)

export const zClockSyncData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
      s: z.optional(z.boolean()),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': zConnectionKey,
  }),
})

/**
 * DeviceTimeResponse
 */
export const zClockSyncResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zDeviceTimeInfo),
  }),
)

export const zGetOffsetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': zConnectionKey,
  }),
})

/**
 * DeviceTimeResponse
 */
export const zGetOffsetResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(
      z.object({
        offset: zTimestamp,
      }),
    ),
  }),
)

export const zSetOffsetData = z.object({
  body: z.object({
    offset: z.number(),
  }),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': zConnectionKey,
  }),
})

/**
 * DeviceTimeResponse
 */
export const zSetOffsetResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(z.string()),
  }),
)

export const zGetHvpStateData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': zConnectionKey,
  }),
})

/**
 * HVP state.
 */
export const zGetHvpStateResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zHvpState),
  }),
)

export const zSetHvpStateData = z.object({
  body: z.object({
    amplitude: z.number().gte(0).lte(1),
    frequency: z.int().gte(0).lte(10000),
    position: z.number().default(200),
  }),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': zConnectionKey,
  }),
})

/**
 * HVP state.
 */
export const zSetHvpStateResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zHvpState),
  }),
)

export const zHvpStartData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': zConnectionKey,
  }),
})

/**
 * HVP state.
 */
export const zHvpStartResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zHvpState),
  }),
)

export const zHvpStopData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': zConnectionKey,
  }),
})

/**
 * HVP state.
 */
export const zHvpStopResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zHvpState),
  }),
)

export const zGetSlideStateData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': zConnectionKey,
  }),
})

/**
 * Slider state.
 */
export const zGetSlideStateResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zSliderState),
  }),
)

export const zGetStrokeData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': z.union([zConnectionKey, zChannelReference]),
  }),
})

/**
 * Device response. In case of a device error, the response will contain an ErrorResponse object.
 */
export const zGetStrokeResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zStrokeSettingsRsp),
  }),
)

export const zSetStrokeData = z.object({
  body: zStrokeSettings,
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': z.union([zConnectionKey, zChannelReference]),
  }),
})

/**
 * Device response. In case of a device error, the response will contain an ErrorResponse object.
 */
export const zSetStrokeResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zStrokeSettingsRsp),
  }),
)

export const zSetupStreamData = z.object({
  body: z.object({
    stream_ref: z.string(),
    notify: z.optional(z.boolean()).default(false),
  }),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': z.union([zConnectionKey, zChannelReference]),
  }),
})

/**
 * Stream state.
 */
export const zSetupStreamResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zHspState),
  }),
)

export const zStreamPlayData = z.object({
  body: z.object({
    start_time: z.int(),
    server_time: zServerTimeEstimate,
    playback_rate: z.optional(zPlaybackRate),
    loop: z.optional(z.boolean()).default(false),
    pause_on_starving: z.optional(zPauseOnStarving),
  }),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': z.union([zConnectionKey, zChannelReference]),
  }),
})

/**
 * Stream state.
 */
export const zStreamPlayResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zHspState),
  }),
)

export const zStreamStopData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': z.union([zConnectionKey, zChannelReference]),
  }),
})

/**
 * Stream state.
 */
export const zStreamStopResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zHspState),
  }),
)

export const zGetStreamStateData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': z.union([zConnectionKey, zChannelReference]),
  }),
})

/**
 * Stream state.
 */
export const zGetStreamStateResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zHspState),
  }),
)

export const zSetStreamTimeData = z.object({
  body: z.object({
    current_time: z.int(),
    server_time: zServerTimeEstimate,
    filter: z.optional(z.number()),
  }),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      timeout: z.optional(z.int().gte(5000).lte(60000)).default(5000),
    }),
  ),
  headers: z.object({
    'X-Connection-Key': z.union([zConnectionKey, zChannelReference]),
  }),
})

/**
 * HSP state.
 */
export const zSetStreamTimeResponse = zDeviceResponse.and(
  z.object({
    result: z.optional(zHspState),
  }),
)
