/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SingleResultRouteImport } from './routes/single-result'
import { Route as SinglePlayerSetupRouteImport } from './routes/single-player-setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoundsRouteImport } from './routes/rounds'
import { Route as PlaylistWorkshopRouteImport } from './routes/playlist-workshop'
import { Route as MultiplayerResultRouteImport } from './routes/multiplayer-result'
import { Route as MultiplayerMatchRouteImport } from './routes/multiplayer-match'
import { Route as MultiplayerLobbyRouteImport } from './routes/multiplayer-lobby'
import { Route as MultiplayerBansRouteImport } from './routes/multiplayer-bans'
import { Route as MultiplayerRouteImport } from './routes/multiplayer'
import { Route as MapEditorRouteImport } from './routes/map-editor'
import { Route as HighscoresRouteImport } from './routes/highscores'
import { Route as GameRouteImport } from './routes/game'
import { Route as ConverterRouteImport } from './routes/converter'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as IndexRouteImport } from './routes/index'

const SingleResultRoute = SingleResultRouteImport.update({
  id: '/single-result',
  path: '/single-result',
  getParentRoute: () => rootRouteImport,
} as any)
const SinglePlayerSetupRoute = SinglePlayerSetupRouteImport.update({
  id: '/single-player-setup',
  path: '/single-player-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoundsRoute = RoundsRouteImport.update({
  id: '/rounds',
  path: '/rounds',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistWorkshopRoute = PlaylistWorkshopRouteImport.update({
  id: '/playlist-workshop',
  path: '/playlist-workshop',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiplayerResultRoute = MultiplayerResultRouteImport.update({
  id: '/multiplayer-result',
  path: '/multiplayer-result',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiplayerMatchRoute = MultiplayerMatchRouteImport.update({
  id: '/multiplayer-match',
  path: '/multiplayer-match',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiplayerLobbyRoute = MultiplayerLobbyRouteImport.update({
  id: '/multiplayer-lobby',
  path: '/multiplayer-lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiplayerBansRoute = MultiplayerBansRouteImport.update({
  id: '/multiplayer-bans',
  path: '/multiplayer-bans',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiplayerRoute = MultiplayerRouteImport.update({
  id: '/multiplayer',
  path: '/multiplayer',
  getParentRoute: () => rootRouteImport,
} as any)
const MapEditorRoute = MapEditorRouteImport.update({
  id: '/map-editor',
  path: '/map-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const HighscoresRoute = HighscoresRouteImport.update({
  id: '/highscores',
  path: '/highscores',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const ConverterRoute = ConverterRouteImport.update({
  id: '/converter',
  path: '/converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/converter': typeof ConverterRoute
  '/game': typeof GameRoute
  '/highscores': typeof HighscoresRoute
  '/map-editor': typeof MapEditorRoute
  '/multiplayer': typeof MultiplayerRoute
  '/multiplayer-bans': typeof MultiplayerBansRoute
  '/multiplayer-lobby': typeof MultiplayerLobbyRoute
  '/multiplayer-match': typeof MultiplayerMatchRoute
  '/multiplayer-result': typeof MultiplayerResultRoute
  '/playlist-workshop': typeof PlaylistWorkshopRoute
  '/rounds': typeof RoundsRoute
  '/settings': typeof SettingsRoute
  '/single-player-setup': typeof SinglePlayerSetupRoute
  '/single-result': typeof SingleResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/converter': typeof ConverterRoute
  '/game': typeof GameRoute
  '/highscores': typeof HighscoresRoute
  '/map-editor': typeof MapEditorRoute
  '/multiplayer': typeof MultiplayerRoute
  '/multiplayer-bans': typeof MultiplayerBansRoute
  '/multiplayer-lobby': typeof MultiplayerLobbyRoute
  '/multiplayer-match': typeof MultiplayerMatchRoute
  '/multiplayer-result': typeof MultiplayerResultRoute
  '/playlist-workshop': typeof PlaylistWorkshopRoute
  '/rounds': typeof RoundsRoute
  '/settings': typeof SettingsRoute
  '/single-player-setup': typeof SinglePlayerSetupRoute
  '/single-result': typeof SingleResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/converter': typeof ConverterRoute
  '/game': typeof GameRoute
  '/highscores': typeof HighscoresRoute
  '/map-editor': typeof MapEditorRoute
  '/multiplayer': typeof MultiplayerRoute
  '/multiplayer-bans': typeof MultiplayerBansRoute
  '/multiplayer-lobby': typeof MultiplayerLobbyRoute
  '/multiplayer-match': typeof MultiplayerMatchRoute
  '/multiplayer-result': typeof MultiplayerResultRoute
  '/playlist-workshop': typeof PlaylistWorkshopRoute
  '/rounds': typeof RoundsRoute
  '/settings': typeof SettingsRoute
  '/single-player-setup': typeof SinglePlayerSetupRoute
  '/single-result': typeof SingleResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/converter'
    | '/game'
    | '/highscores'
    | '/map-editor'
    | '/multiplayer'
    | '/multiplayer-bans'
    | '/multiplayer-lobby'
    | '/multiplayer-match'
    | '/multiplayer-result'
    | '/playlist-workshop'
    | '/rounds'
    | '/settings'
    | '/single-player-setup'
    | '/single-result'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect'
    | '/converter'
    | '/game'
    | '/highscores'
    | '/map-editor'
    | '/multiplayer'
    | '/multiplayer-bans'
    | '/multiplayer-lobby'
    | '/multiplayer-match'
    | '/multiplayer-result'
    | '/playlist-workshop'
    | '/rounds'
    | '/settings'
    | '/single-player-setup'
    | '/single-result'
  id:
    | '__root__'
    | '/'
    | '/connect'
    | '/converter'
    | '/game'
    | '/highscores'
    | '/map-editor'
    | '/multiplayer'
    | '/multiplayer-bans'
    | '/multiplayer-lobby'
    | '/multiplayer-match'
    | '/multiplayer-result'
    | '/playlist-workshop'
    | '/rounds'
    | '/settings'
    | '/single-player-setup'
    | '/single-result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectRoute: typeof ConnectRoute
  ConverterRoute: typeof ConverterRoute
  GameRoute: typeof GameRoute
  HighscoresRoute: typeof HighscoresRoute
  MapEditorRoute: typeof MapEditorRoute
  MultiplayerRoute: typeof MultiplayerRoute
  MultiplayerBansRoute: typeof MultiplayerBansRoute
  MultiplayerLobbyRoute: typeof MultiplayerLobbyRoute
  MultiplayerMatchRoute: typeof MultiplayerMatchRoute
  MultiplayerResultRoute: typeof MultiplayerResultRoute
  PlaylistWorkshopRoute: typeof PlaylistWorkshopRoute
  RoundsRoute: typeof RoundsRoute
  SettingsRoute: typeof SettingsRoute
  SinglePlayerSetupRoute: typeof SinglePlayerSetupRoute
  SingleResultRoute: typeof SingleResultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/single-result': {
      id: '/single-result'
      path: '/single-result'
      fullPath: '/single-result'
      preLoaderRoute: typeof SingleResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/single-player-setup': {
      id: '/single-player-setup'
      path: '/single-player-setup'
      fullPath: '/single-player-setup'
      preLoaderRoute: typeof SinglePlayerSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rounds': {
      id: '/rounds'
      path: '/rounds'
      fullPath: '/rounds'
      preLoaderRoute: typeof RoundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist-workshop': {
      id: '/playlist-workshop'
      path: '/playlist-workshop'
      fullPath: '/playlist-workshop'
      preLoaderRoute: typeof PlaylistWorkshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multiplayer-result': {
      id: '/multiplayer-result'
      path: '/multiplayer-result'
      fullPath: '/multiplayer-result'
      preLoaderRoute: typeof MultiplayerResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multiplayer-match': {
      id: '/multiplayer-match'
      path: '/multiplayer-match'
      fullPath: '/multiplayer-match'
      preLoaderRoute: typeof MultiplayerMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multiplayer-lobby': {
      id: '/multiplayer-lobby'
      path: '/multiplayer-lobby'
      fullPath: '/multiplayer-lobby'
      preLoaderRoute: typeof MultiplayerLobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multiplayer-bans': {
      id: '/multiplayer-bans'
      path: '/multiplayer-bans'
      fullPath: '/multiplayer-bans'
      preLoaderRoute: typeof MultiplayerBansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multiplayer': {
      id: '/multiplayer'
      path: '/multiplayer'
      fullPath: '/multiplayer'
      preLoaderRoute: typeof MultiplayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map-editor': {
      id: '/map-editor'
      path: '/map-editor'
      fullPath: '/map-editor'
      preLoaderRoute: typeof MapEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/highscores': {
      id: '/highscores'
      path: '/highscores'
      fullPath: '/highscores'
      preLoaderRoute: typeof HighscoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/converter': {
      id: '/converter'
      path: '/converter'
      fullPath: '/converter'
      preLoaderRoute: typeof ConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectRoute: ConnectRoute,
  ConverterRoute: ConverterRoute,
  GameRoute: GameRoute,
  HighscoresRoute: HighscoresRoute,
  MapEditorRoute: MapEditorRoute,
  MultiplayerRoute: MultiplayerRoute,
  MultiplayerBansRoute: MultiplayerBansRoute,
  MultiplayerLobbyRoute: MultiplayerLobbyRoute,
  MultiplayerMatchRoute: MultiplayerMatchRoute,
  MultiplayerResultRoute: MultiplayerResultRoute,
  PlaylistWorkshopRoute: PlaylistWorkshopRoute,
  RoundsRoute: RoundsRoute,
  SettingsRoute: SettingsRoute,
  SinglePlayerSetupRoute: SinglePlayerSetupRoute,
  SingleResultRoute: SingleResultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
